// ui/src/components/map/StyleToggle.jsx
import React, { useState, memo } from 'react'
import PropTypes from 'prop-types'
import { Box, Image } from 'theme-ui'

import LightIcon from 'images/light-v9.jpg'
import SatelliteIcon from 'images/satellite-streets-v11.jpg'

const coreCSS = {
  cursor: 'pointer',
  position: 'absolute',
  zIndex: 999,
  overflow: 'hidden',
}

const desktopCSS = {
  ...coreCSS,
  left: '10px',
  bottom: '40px',
  borderRadius: '64px',
  border: '2px solid #FFF',
  boxShadow: '0 1px 5px rgba(0, 0, 0, 0.65)',
  width: '64px',
  height: '64px',
}

const mobileCSS = {
  ...coreCSS,
  right: '10px',
  top: '24px',
  width: '40px',
  height: '40px',
  borderRadius: '32px',
  boxShadow: '0 1px 5px #000',
  border: '1px solid #FFF',
}

const styles = [
  { id: 'light-v9', label: 'Light Basemap', icon: LightIcon },
  {
    id: 'satellite-streets-v11',
    label: 'Satellite Basemap',
    icon: SatelliteIcon,
  },
]

const StyleToggle = ({ isMobile, onStyleChange }) => {
  const [index, setIndex] = useState(0)

  const handleToggle = () => {
    setIndex((prevIndex) => {
      const nextIndex = prevIndex === 0 ? 1 : 0
      onStyleChange(styles[nextIndex].id)
      return nextIndex
    })
  }

  const { label, icon } = styles[index === 0 ? 1 : 0]

  return (
    <Box sx={isMobile ? mobileCSS : desktopCSS}>
      <Image
        sx={{ height: '100%', width: '100%' }}
        alt={label}
        src={icon}
        onClick={handleToggle}
      />
    </Box>
  )
}

StyleToggle.propTypes = {
  onStyleChange: PropTypes.func.isRequired,
  isMobile: PropTypes.bool,
}

StyleToggle.defaultProps = {
  isMobile: false,
}

export default memo(StyleToggle)

// ui/src/lib/components/map/StyleToggle.svelte
<script lang="ts">
	import LightIcon from '$images/light-v9.jpg'
	import SatelliteIcon from '$images/satellite-streets-v11.jpg'
	import { Button } from '$lib/components/ui/button'

	const styles = [
		{ id: 'light-v9', label: 'Light Basemap', icon: LightIcon },
		{
			id: 'satellite-streets-v11',
			label: 'Satellite Basemap',
			icon: SatelliteIcon
		}
	]

	const { onChange } = $props()
	let index = $state(0)

	const handleToggle = () => {
		index = index === 0 ? 1 : 0
		onChange(styles[index].id)
	}

	const { label, icon } = $derived(styles[index === 0 ? 1 : 0])
</script>

<Button
	onclick={handleToggle}
	class="absolute z-1 overflow-hidden right-[10px] md:right-auto md:left-[10px] top-[14px] md:top-auto md:bottom-[40px] w-[40px] md:w-[64px] h-[40px] md:h-[64px] rounded-full border md:border-2 border-white shadow-lg shadow-grey-8 ring-1 ring-grey-4 p-0 "
>
	<img src={icon} alt={label} class="w-full h-full" />
</Button>
