// ui/src/lib/components/filter/Filter.svelte
<script lang="ts">
	import ExclamationTriangle from '~icons/fa-solid/exclamation-triangle'
	import FilterIcon from '~icons/fa-solid/filter'
	import Plus from '~icons/fa-solid/plus'
	import { Checkbox } from '$lib/components/ui/checkbox'
	import { Label } from '$lib/components/ui/label'
	import { InfoTooltip } from '$lib/components/tooltip'
	import { cn } from '$lib/utils'

	import { logGAEvent } from '$lib/util/log'

	const {
		id,
		label,
		description,
		values,
		valueLabel: indicatorValueLabel,
		enabled,
		activeValues,
		canBeVisible,
		onChange
	} = $props()

	let checkboxNode: HTMLElement | null = $state(null)

	const handleFilterToggle = () => {
		const isNowEnabled = !enabled
		onChange({ id, enabled: isNowEnabled, activeValues })

		if (isNowEnabled) {
			logGAEvent('enable-filter', { filter: id })
		}

		// blur on uncheck
		if (checkboxNode && enabled) {
			checkboxNode.blur()
		}
	}

	const handleToggleValue = (value: number) => () => {
		const newActiveValues = {
			...activeValues,
			[value]: !activeValues[value]
		}
		logGAEvent('set-filter-values', {
			filter: id,
			values: `${id}:${Object.entries(newActiveValues)
				.filter(([_, v]) => v)
				.map(([k]) => k.toString())
				.join(',')}`
		})

		onChange({ id, enabled, activeValues: newActiveValues })
	}

	const handleKeyDown = ({ key }: { key: string }) => {
		if (key === 'Enter' || key === ' ') {
			const isNowEnabled = !enabled
			onChange({ id, enabled: isNowEnabled, activeValues })

			if (isNowEnabled) {
				logGAEvent('enable-filter', { filter: id })
			}
		}
	}
</script>

<div class="pr-2 not-first:border-t-2 border-t-grey-1">
	<div class="flex justify-between items-center gap-2">
		<div
			tabindex="0"
			role="button"
			onclick={handleFilterToggle}
			onkeydown={handleKeyDown}
			class={cn(
				'label flex-auto pl-4 py-1 border-2 border-transparent cursor-pointer group hover:bg-blue-0',
				{
					'font-bold': enabled
				}
			)}
		>
			<div class="flex flex-auto items-center gap-2">
				<div class="relative">
					<FilterIcon
						width="1em"
						height="1em"
						class={cn('top-0 relative text-grey-4 group-hover:text-grey-9', {
							'text-grey-9': enabled
						})}
					/>
					<Plus
						width="0.7em"
						height="0.7em"
						class={cn('absolute top-[0.1rem] left-[-0.5rem] text-grey-4  group-hover:text-grey-9', {
							hidden: enabled
						})}
					/>
				</div>
				{label}
			</div>
		</div>
		<InfoTooltip title={label} {description} />
	</div>

	{#if enabled}
		<div class="ml-11 mr-4 pb-2">
			{#if canBeVisible}
				{#if indicatorValueLabel}
					<div class="leading-snug mb-2">
						{indicatorValueLabel}
					</div>
				{/if}

				{#each values as { value, label: valueLabel }}
					<div class="flex gap-3 not-first:mt-2">
						<Checkbox
							bind:ref={checkboxNode}
							id={`checkbox-${id}-${value}`}
							checked={activeValues[value]}
							onCheckedChange={handleToggleValue(value)}
						/>
						<Label
							for={`checkbox-${id}-${value}`}
							class="text-md cursor-pointer leading-tight mt-[-0.1rem]"
						>
							{valueLabel}
						</Label>
					</div>
				{/each}
			{:else}
				<div class="flex gap-1 items-center justify-center text-grey-8">
					<ExclamationTriangle width="1em" height="1em" />
					not visible in this area
				</div>
			{/if}
		</div>
	{/if}
</div>

// ui/src/content/FiltersTab/Filter.jsx
import React, { useCallback, useRef } from 'react'
import PropTypes from 'prop-types'
import { Box, Checkbox, Flex, Label, Text } from 'theme-ui'
import {
  ExclamationTriangle,
  Filter as FilterIcon,
  Plus,
} from '@emotion-icons/fa-solid'

import { InfoTooltip } from 'components/tooltip'
import { logGAEvent } from 'util/log'
import { useIsEqualCallback } from 'util/hooks'

const Filter = ({
  id,
  label,
  description,
  values,
  valueLabel: indicatorValueLabel,
  enabled,
  activeValues,
  canBeVisible,
  onChange,
}) => {
  const checkboxRef = useRef(null)

  const tooltipContent = (
    <Box sx={{ fontSize: 0 }}>
      <Text sx={{ mb: 0, fontSize: 1, fontWeight: 'bold' }}>{label}</Text>
      {description ? (
        <Text sx={{ mb: '0.5rem' }}>
          {/* handle links */}
          {description.search(/<a/g) !== -1 ? (
            <div dangerouslySetInnerHTML={{ __html: description }} />
          ) : (
            description
          )}
        </Text>
      ) : null}
    </Box>
  )

  // retain previous active values
  const toggleEnabled = useIsEqualCallback(() => {
    const isNowEnabled = !enabled
    onChange({ id, enabled: isNowEnabled, activeValues })

    if (isNowEnabled) {
      logGAEvent('enable-filter', { filter: id })
    }

    // blur on uncheck
    if (checkboxRef.current && enabled) {
      checkboxRef.current.blur()
    }
  }, [id, enabled, activeValues, onChange])

  const handleToggleValue = (value) => () => {
    const newActiveValues = {
      ...activeValues,
      [value]: !activeValues[value],
    }
    logGAEvent('set-filter-values', {
      filter: id,
      values: `${id}:${Object.entries(newActiveValues)
        .filter(([k, v]) => v)
        .map(([k]) => k.toString())
        .join(',')}`,
    })

    onChange({ id, enabled, activeValues: newActiveValues })
  }

  const handleKeyDown = useCallback(
    ({ key }) => {
      if (key === 'Enter' || key === ' ') {
        const isNowEnabled = !enabled
        onChange({ id, enabled: isNowEnabled, activeValues })

        if (isNowEnabled) {
          logGAEvent('enable-filter', { filter: id })
        }
      }
    },
    [id, enabled, activeValues, onChange]
  )

  return (
    <Box
      sx={{
        pr: '0.5rem',
        '&:hover': {
          borderColor: 'highlight',
          '& .filter-icon': {
            color: 'grey.9',
          },
          '& .label': {
            bg: 'blue.0',
          },
        },
        '&:not(:first-of-type)': {
          borderTop: '2px solid',
          borderTopColor: 'grey.1',
        },
      }}
    >
      <Box>
        <Flex sx={{ justifyContent: 'space-between', alignItems: 'center' }}>
          <Box
            tabIndex={0}
            onClick={toggleEnabled}
            onKeyDown={handleKeyDown}
            className="label"
            sx={{
              flex: '1 1 auto',
              pl: '1rem',
              py: '0.25rem',
              fontSize: 1,
              fontWeight: enabled ? 'bold' : 'normal',
              lineHeight: 1.5,
              border: '2px solid transparent',
              cursor: 'pointer',
              '&:focus-within': {
                border: '2px dashed',
                borderColor: 'highlight',
              },
            }}
          >
            <Flex
              sx={{
                flex: '1 1 auto',
                alignItems: 'center',
                gap: '0.5rem',
              }}
            >
              <Box
                className="filter-icon"
                sx={{ color: enabled ? 'grey.9' : 'grey.4' }}
              >
                {enabled ? (
                  <Box
                    sx={{
                      position: 'relative',
                    }}
                  >
                    <FilterIcon
                      size="1em"
                      style={{ position: 'relative', top: 0 }}
                    />
                  </Box>
                ) : (
                  <Box sx={{ position: 'relative' }}>
                    <FilterIcon size="1em" style={{ top: 0 }} />
                    <Text
                      sx={{
                        position: 'absolute',
                        top: '-0.2rem',
                        left: '-0.5rem',
                        fontSize: 3,
                        fontWeight: 'bold',
                      }}
                    >
                      <Plus size="0.6em" />
                    </Text>
                  </Box>
                )}
              </Box>
              <Text>{label}</Text>
            </Flex>
          </Box>

          <InfoTooltip content={tooltipContent} direction="right" />
        </Flex>

        {enabled ? (
          <Box sx={{ ml: '2.5rem', mr: '1rem', pb: '0.5rem' }}>
            {canBeVisible ? (
              <Box>
                {indicatorValueLabel ? (
                  <Text sx={{ lineHeight: 1.2, mb: '0.5rem' }}>
                    {indicatorValueLabel}:
                  </Text>
                ) : null}

                {values.map(({ value, label: valueLabel }) => (
                  <Box key={value}>
                    <Label
                      sx={{
                        flex: '1 1 auto',
                        fontSize: 1,
                        lineHeight: 1.3,
                        border: '2px solid transparent',
                        '&:focus-within': {
                          border: '2px dashed',
                          borderColor: 'highlight',
                        },
                      }}
                    >
                      <Checkbox
                        ref={checkboxRef}
                        readOnly={false}
                        checked={activeValues[value]}
                        onChange={handleToggleValue(value)}
                        sx={{
                          cursor: 'pointer',
                          mr: '0.25em',
                          width: '1.5em',
                          height: '1.5em',
                          'input:focus ~ &': {
                            backgroundColor: 'transparent',
                          },
                        }}
                      />

                      {valueLabel}
                    </Label>
                  </Box>
                ))}
              </Box>
            ) : (
              <Flex
                sx={{ gap: '0.25rem', color: 'grey.8', alignItems: 'center' }}
              >
                <ExclamationTriangle size="1em" />
                <Text>not visible in this area</Text>
              </Flex>
            )}
          </Box>
        ) : null}
      </Box>
    </Box>
  )
}

Filter.propTypes = {
  id: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
  description: PropTypes.string,
  values: PropTypes.arrayOf(
    PropTypes.shape({
      value: PropTypes.number.isRequired,
      label: PropTypes.string.isRequired,
    })
  ).isRequired,
  valueLabel: PropTypes.string,
  activeValues: PropTypes.objectOf(PropTypes.bool).isRequired,
  enabled: PropTypes.bool,
  canBeVisible: PropTypes.bool,
  onChange: PropTypes.func.isRequired,
}

Filter.defaultProps = {
  description: null,
  enabled: false,
  canBeVisible: true,
  valueLabel: null,
}

export default Filter
