// ui/src/lib/components/tabs/FiltersTab.svelte
<script lang="ts">
	import { getContext } from 'svelte'

	import ExclamationTriangle from '~icons/fa-solid/exclamation-triangle'
	import FilterIcon from '~icons/fa-solid/filter'
	import TimesCircle from '~icons/fa-solid/times-circle'
	import { Button } from '$lib/components/ui/button'
	import BlueprintIcon from '$images/blueprint.svg'
	import FreshwaterIcon from '$images/f.svg'
	import MarineIcon from '$images/m.svg'
	import OtherInfoIcon from '$images/otherInfo.svg'
	import TerrestrialIcon from '$images/t.svg'
	import type { MapState } from '$lib/components/map'
	import { setIntersection } from '$lib/util/data'
	import type { Filter } from '$lib/types'
	import { cn } from '$lib/utils'
	import { ecosystemIndex } from '$lib/config/constants'
	import {
		priorityFilters as rawPriorityFilters,
		ecosystemFilters,
		otherInfoFilters as rawOtherInfoFilters
	} from '$lib/config/filters'
	import { FilterGroup, FilterMethodDropdown } from '$lib/components/filter'
	import { PrintMapDialog } from '$lib/components/dialog'

	const { class: className } = $props()
	const mapState: MapState = getContext('map-state')

	type FilterVisibilityStub = {
		canBeVisible: boolean
		enabled: boolean
	}

	let { priorityFilters, terrestrialFilters, freshwaterFilters, marineFilters, otherInfoFilters } =
		$derived.by(() => {
			return {
				priorityFilters: rawPriorityFilters
					.map((entry) => ({
						...entry,
						...mapState.filters[entry.id],
						canBeVisible: mapState.visibleSubregions.size > 0
					}))
					.filter(
						({ canBeVisible, enabled }: FilterVisibilityStub) => canBeVisible || enabled // mapState.filters[id].enabled
					),

				terrestrialFilters: ecosystemFilters.t.indicators
					.map(
						({
							id,
							subregions: indicatorSubregions,
							...rest
						}: {
							id: string
							subregions: Set<string>
						}) => ({
							id,
							...rest,
							...mapState.filters[id],
							canBeVisible:
								setIntersection(indicatorSubregions, mapState.visibleSubregions).size > 0
						})
					)
					.filter(
						({ canBeVisible, enabled }: FilterVisibilityStub) => canBeVisible || enabled // mapState.filters[id].enabled
					),

				freshwaterFilters: ecosystemFilters.f.indicators
					.map(
						({
							id,
							subregions: indicatorSubregions,
							...rest
						}: {
							id: string
							subregions: Set<string>
						}) => ({
							id,
							...rest,
							...mapState.filters[id],
							canBeVisible:
								setIntersection(indicatorSubregions, mapState.visibleSubregions).size > 0
						})
					)
					.filter(
						({ canBeVisible, enabled }: FilterVisibilityStub) => canBeVisible || enabled // mapState.filters[id].enabled
					),

				marineFilters: ecosystemFilters.m.indicators
					.map(
						({
							id,
							subregions: indicatorSubregions,
							...rest
						}: {
							id: string
							subregions: Set<string>
						}) => ({
							id,
							...rest,
							...mapState.filters[id],
							canBeVisible:
								setIntersection(indicatorSubregions, mapState.visibleSubregions).size > 0
						})
					)
					.filter(
						({ canBeVisible, enabled }: FilterVisibilityStub) => canBeVisible || enabled // mapState.filters[id].enabled
					),

				otherInfoFilters: rawOtherInfoFilters
					.map((entry) => ({
						...entry,
						...mapState.filters[entry.id],
						canBeVisible:
							(entry.id !== 'urban' &&
								entry.id !== 'wildfireRisk' &&
								mapState.visibleRegions.size > 0) ||
							// urban / wildfire not in Caribbean
							((entry.id === 'urban' || entry.id === 'wildfireRisk') &&
								[...mapState.visibleRegions].filter((s) => s !== 'caribbean').length > 0)
					}))
					.filter(({ canBeVisible, enabled }: FilterVisibilityStub) => canBeVisible || enabled) // mapState.filters[id].enabled)
			}
		})

	const handleFilterChange = ({ id, enabled, activeValues }: Filter & { id: string }) => {
		mapState.setLayerFilterValues(id, { enabled, activeValues })
	}

	const handleResetFilters = () => {
		mapState.resetFilters()
	}
</script>

<section class={cn('flex flex-col h-full', className)}>
	<div class="flex justify-between flex-none pt-4 pb-2 px-2 border-b border-b-grey-2">
		<div class="flex items-center gap-2">
			<FilterIcon class="size-5" />
			<h2 class="text-2xl leading-tight">Filter the Blueprint</h2>
		</div>
		<div
			class={cn('flex justify-end items-center', {
				hidden: mapState.numEnabledFilters === 0
			})}
		>
			<Button onclick={handleResetFilters} class="text-sm px-2 gap-1 py-0 h-7">
				<TimesCircle width="1em" height="1em" class="p-0 m-0" />
				reset {mapState.numEnabledFilters} filter{mapState.numEnabledFilters > 1 ? 's' : ''}
			</Button>
		</div>
	</div>

	<div class="flex-auto h-full overflow-y-auto">
		{#if mapState.filtersLoading}
			<div class="mt-4 text-center text-xl text-grey-8">Loading...</div>
		{:else if mapState.hasVisibleFilters}
			<div class="flex flex-col overflow-y-auto flex-auto h-full relative">
				<div class="px-4 py-2 leading-tight text-grey-8">
					Filters can help you find the part of the Blueprint that aligns with your mission,
					interest, or specific question. Enable the filters below to narrow down the Blueprint to
					the part that falls within a range of values for one or more layers.
				</div>

				<div class="bg-grey-1 py-1 px-2 flex justify-between gap-4">
					<FilterMethodDropdown />
					<PrintMapDialog />
				</div>

				<FilterGroup
					label="Filter by priorities"
					icon={BlueprintIcon}
					color="#4d004b0d"
					borderColor="#4d004b2b"
					entries={priorityFilters}
					onChange={handleFilterChange}
				/>

				<FilterGroup
					label="Filter by terrestrial indicators"
					icon={TerrestrialIcon}
					color={ecosystemIndex.t.color}
					borderColor={ecosystemIndex.t.borderColor}
					entries={terrestrialFilters}
					onChange={handleFilterChange}
				/>

				<FilterGroup
					label="Filter by freshwater indicators"
					icon={FreshwaterIcon}
					color={ecosystemIndex.f.color}
					borderColor={ecosystemIndex.f.borderColor}
					entries={freshwaterFilters}
					onChange={handleFilterChange}
				/>

				<FilterGroup
					label="Filter by coastal & marine indicators"
					icon={MarineIcon}
					color={ecosystemIndex.m.color}
					borderColor={ecosystemIndex.m.borderColor}
					entries={marineFilters}
					onChange={handleFilterChange}
				/>

				<FilterGroup
					label="More filters"
					icon={OtherInfoIcon}
					color="#f3c6a830"
					borderColor="#f3c6a891"
					entries={otherInfoFilters}
					onChange={handleFilterChange}
				/>
			</div>
		{:else}
			<div class="py-8 pl-4 pr-8 flex justify-center">
				<div class="flex items-center gap-2">
					<ExclamationTriangle class="size-6 flex-none text-[orange]" />
					<div class="flex-auto text-grey-8 text-lg">No filters are available for this area.</div>
				</div>
			</div>
		{/if}
	</div>
</section>

// ui/src/content/FiltersTab/index.jsx
import React, { useMemo } from 'react'
import { Box, Flex, Text } from 'theme-ui'
import { ExclamationTriangle } from '@emotion-icons/fa-solid'

import {
  blueprint,
  corridors,
  ecosystems as rawEcosystems,
  indicators as rawIndicators,
  subregions as rawSubregions,
  urban,
  slrDepth,
  slrNodata,
} from 'config'
import { useMapData } from 'components/data'
import { indexBy, sortByFunc, setIntersection } from 'util/data'
import FilterGroup from './FilterGroup'

const FiltersTab = () => {
  const subregionsIndex = indexBy(rawSubregions, 'subregion')

  const { filters, setFilters, visibleSubregions } = useMapData()

  // nest indicators under ecosystems
  const { priorities, otherInfo, ecosystems } = useMemo(
    () => {
      const indicators = indexBy(rawIndicators, 'id')

      return {
        priorities: [
          {
            id: 'blueprint',
            label: 'Blueprint priority',
            description:
              'The Blueprint identifies priority areas based on a suite of natural and cultural resource indicators representing terrestrial, freshwater, and marine ecosystems.',
            values: blueprint
              .slice()
              .sort(sortByFunc('value'))
              .slice(1, blueprint.length)
              .reverse(),
          },
          {
            id: 'corridors',
            label: 'Hubs and corridors',
            values: corridors.filter(({ value }) => value > 0),
            description:
              'The Blueprint uses a least-cost path connectivity analysis to identify corridors that link hubs across the shortest distance possible, while also routing through as much Blueprint priority as possible.',
          },
        ],
        ecosystems: rawEcosystems.map(
          ({ indicators: ecosystemIndicators, ...ecosystem }) => ({
            ...ecosystem,
            indicators: ecosystemIndicators.map((id) => ({
              ...indicators[id],
              // sort indicator values in descending order
              values: indicators[id].values.slice().reverse(),
            })),
          })
        ),
        otherInfo: [
          {
            id: 'urban',
            label: 'Probability of urbanization by 2060',
            values: urban
              .slice()
              // values are not in order and need to be sorted in ascending order
              .sort(sortByFunc('value')),
            description:
              'Past and current (2021) urban levels based on developed land cover classes from the National Land Cover Database. Future urban growth estimates derived from the FUTURES model developed by the Center for Geospatial Analytics, NC State University.  Data extent limited to the inland continental Southeast.',
          },
          {
            id: 'slr',
            label: 'Flooding extent by projected sea-level rise',
            values: slrDepth
              .map(({ label, ...rest }) => ({
                ...rest,
                label: `${label} feet`,
              }))
              .concat(slrNodata),
            description:
              'Sea level rise estimates derived from the NOAA sea-level rise inundation data.',
          },
        ],
      }
    },

    // intentionally omitting dependencies; nothing changes after mount
    /* eslint-disable-next-line react-hooks/exhaustive-deps */
    []
  )

  if (
    visibleSubregions.size === 0 &&
    Object.values(filters).filter(({ enabled }) => enabled).length === 0
  ) {
    return (
      <Flex sx={{ py: '2rem', pl: '1rem', pr: '2rem', alignItems: 'center' }}>
        <Box sx={{ flex: '0 0 auto', mr: '1rem', color: 'orange' }}>
          <ExclamationTriangle size="2em" />
        </Box>
        <Text sx={{ color: 'grey.8', flex: '1 1 auto' }}>
          <b>No filters are available for this area.</b>
        </Text>
      </Flex>
    )
  }

  return (
    <>
      <Flex
        sx={{
          flexDirection: 'column',
          overflowY: 'auto',
          flex: '1 1 auto',
          height: '100%',
          position: 'relative', // prevents layout scroll issue on page
        }}
      >
        <Box
          sx={{ px: '1rem', py: '0.5rem', lineHeight: 1.2, color: 'grey.8' }}
        >
          Filters can help you find the part of the Blueprint that aligns with
          your mission, interest, or specific question. Enable the filters below
          to narrow down the Blueprint to the part that falls within a range of
          values for one or more layers.
        </Box>
        <FilterGroup
          id="blueprint"
          label="Filter by priorities"
          color="#4d004b0d"
          borderColor="#4d004b2b"
          entries={priorities.map((entry) => ({
            ...entry,
            canBeVisible: visibleSubregions.size > 0,
          }))}
          filters={filters}
          onChange={setFilters}
        />

        {ecosystems.map((ecosystem) => (
          <FilterGroup
            key={ecosystem.id}
            {...ecosystem}
            label={`Filter by ${ecosystem.label.toLowerCase()} indicators`}
            entries={ecosystem.indicators.map(
              ({ subregions: indicatorSubregions, ...rest }) => ({
                ...rest,
                canBeVisible:
                  setIntersection(indicatorSubregions, visibleSubregions).size >
                  0,
              })
            )}
            filters={filters}
            onChange={setFilters}
          />
        ))}

        <FilterGroup
          id="otherInfo"
          label="More filters"
          color="#f3c6a830"
          borderColor="#f3c6a891"
          entries={otherInfo.map((entry) => ({
            ...entry,
            canBeVisible:
              [...visibleSubregions].filter(
                (name) => !subregionsIndex[name].marine
              ).length > 0,
          }))}
          filters={filters}
          onChange={setFilters}
        />
      </Flex>
    </>
  )
}

export default FiltersTab
