// ui/src/components/report/UploadError.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Alert, Close, Box, Text, Link } from 'theme-ui'
import { ExclamationTriangle } from '@emotion-icons/fa-solid'

import config from '../../../gatsby-config'

const { contactEmail } = config.siteMetadata

const UploadError = ({ error, handleClearError }) => (
  <Alert variant="error" sx={{ mt: '2rem', mb: '4rem', py: '1rem' }}>
    <ExclamationTriangle
      size="2rem"
      style={{
        margin: '0 1rem 0 0',
      }}
    />
    <Box sx={{ mr: '2rem' }}>
      Uh oh! There was an error!
      <br />
      {error ? (
        `The server says: ${error}`
      ) : (
        <>
          <Text as="span">
            Please try again. If that does not work, try a different file or
          </Text>{' '}
          <Link sx={{ color: '#FFF' }} href={`mailto:${contactEmail}`}>
            Contact Us
          </Link>
          .
        </>
      )}
    </Box>

    <Close
      variant="buttons.alertClose"
      ml="auto"
      sx={{ flex: '0 0 auto' }}
      onClick={handleClearError}
    />
  </Alert>
)

UploadError.propTypes = {
  error: PropTypes.string,
  handleClearError: PropTypes.func.isRequired,
}

UploadError.defaultProps = {
  error: null,
}

export default UploadError

// ui/src/routes/custom_report/UploadError.svelte
<script lang="ts">
	import ExclamationTriangle from '~icons/fa-solid/exclamation-triangle'
	import { Button } from '$lib/components/ui/button'
	import { Root, Title, Description } from '$lib/components/ui/alert'
	import { siteMetadata } from '$lib/meta'

	const { contactEmail } = siteMetadata

	const { error, onReset } = $props()
</script>

<div class="container mt-8">
	<Root variant="destructive" class="border-error flex gap-4">
		<ExclamationTriangle width="2rem" height="2rem" class="flex-none" />
		<div>
			<Title class="text-2xl">Uh oh! There was an error!</Title>
			<Description class="text-xl">
				<p class="text-error">
					{#if error}
						The server says {error}
					{:else}
						Please try again. If that does not work, try a different file or <a
							href={`mailto:${contactEmail}`}>contact us</a
						>.
					{/if}
				</p>
			</Description>
		</div>
	</Root>

	<div class="flex justify-center border-t border-t-grey-2 mt-8 pt-8">
		<Button onclick={onReset} class="text-xl">Try again?</Button>
	</div>
</div>
