// ui/src/lib/components/tabs/FindLocationTab.svelte
<script lang="ts">
	import { getContext } from 'svelte'

	import LocationArrowIcon from '~icons/fa-solid/location-arrow'
	import SpinnerIcon from '~icons/fa-solid/spinner'
	import { Search } from '$lib/components/search'
	import { Button } from '$lib/components/ui/button'
	import { hasGeolocation } from '$lib/util/dom'
	import type { LocationData } from '$lib/types'

	const navigatorOptions = {
		enableHighAccuracy: false,
		maximumAge: 0,
		timeout: 6000
	}

	let isError: boolean = $state(false)
	let isPending: boolean = $state(false)
	const locationData: LocationData = getContext('location-data')

	const handleGetMyLocation = () => {
		isError = false
		isPending = true

		navigator.geolocation.getCurrentPosition(
			({ coords: { latitude, longitude } }) => {
				isPending = false
				locationData.location = {
					latitude,
					longitude
				}
			},
			(err) => {
				isError = true
				isPending = false
				console.error(err)
			},
			navigatorOptions
		)
	}
</script>

<section class="flex flex-col h-full justify-between overflow-y-auto pt-4 pb-8">
	<div class="flex-auto">
		<h3 class="mb-2 pl-4 pr-8 text-xl">Find a location on the map</h3>
		<div
			class="[&_.search-input-container]:px-4 [&_.search-input-container]:py-2 [&_.search-input-container]:bg-grey-1"
		>
			<Search />
		</div>
	</div>

	<div class="flex-none">
		{#if hasGeolocation}
			{#if isPending}
				<div class="flex justify-center text-grey-8 px-4 gap-4">
					<SpinnerIcon class="size-6 animate-spin" />
					Fetching your location from your device
				</div>
			{:else}
				<div class="flex flex-col items-center mt-8">
					<Button onclick={handleGetMyLocation} class="text-lg">
						<LocationArrowIcon class="size-5" />
						Go to my location
					</Button>
				</div>

				{#if isError}
					<div class="text-grey-8 mt-8 px-4">
						We&apos;re sorry, there was an error trying to get your current location. Your browser
						may not have sufficient permissions on your device to determine your location. You can
						also try again.
					</div>
				{/if}
			{/if}
		{/if}
	</div>
</section>

// ui/src/content/FindLocationTab/index.jsx
import React, { memo, useCallback, useState } from 'react'
import { Box, Button, Flex, Heading, Text, Spinner } from 'theme-ui'
import { LocationArrow } from '@emotion-icons/fa-solid'

import { Search, useSearch } from 'components/search'
import { hasGeolocation } from 'util/dom'

const navigatorOptions = {
  enableHighAccuracy: false,
  maximumAge: 0,
  timeout: 6000,
}

// Tab is only displayed in mobile mode; a different map widget is used for
// desktop mode
const FindLocationTab = () => {
  const [{ error, isPending }, setState] = useState({
    error: null,
    isPending: false,
  })
  const { setLocation, query } = useSearch()

  const handleGetMyLocation = useCallback(() => {
    setState(() => ({ isPending: true, error: false }))

    navigator.geolocation.getCurrentPosition(
      ({ coords: { latitude, longitude } }) => {
        setState(() => ({ isPending: false }))
        setLocation({
          latitude,
          longitude,
          timestamp: new Date().getTime(),
        })
      },
      (err) => {
        setState(() => ({ isPending: false, error: true }))
        console.error(err)
      },
      navigatorOptions
    )
  }, [setLocation])

  return (
    <Box as="section" sx={{ py: '1.5rem' }}>
      <Heading as="h3" sx={{ mb: '0.5rem', pl: '1rem', pr: '2rem' }}>
        Find a location on the map
      </Heading>
      <Box
        sx={{
          '.search-field-container': {
            px: '1rem',
            py: '0.5rem',
            bg: 'grey.1',
          },
          '.search-field': {
            bg: '#FFF',
          },
        }}
      >
        <Search />
      </Box>

      {hasGeolocation && query === '' ? (
        <Flex sx={{ mt: '2rem', justifyContent: 'center' }}>
          {isPending ? (
            <Flex
              sx={{
                color: 'grey.8',
                justifyContent: 'center',
                px: '1rem',
                gap: '1rem',
              }}
            >
              <Spinner />
              <Text>Fetching your location from your device</Text>
            </Flex>
          ) : (
            <Flex sx={{ alignItems: 'center', flexDirection: 'column' }}>
              <Button onClick={handleGetMyLocation} sx={{ fontSize: 1 }}>
                <Flex sx={{ alignItems: 'center', gap: '1rem' }}>
                  <Box sx={{ flex: '0 0 auto' }}>
                    <LocationArrow size="1.25em" />
                  </Box>
                  <Text sx={{ flex: '1 1 auto' }}>Go to my location</Text>
                </Flex>
              </Button>
              {error ? (
                <Text sx={{ color: 'grey.8', mt: '2rem', px: '1rem' }}>
                  We&apos;re sorry, there was an error trying to get your
                  current location. Your browser may not have sufficient
                  permissions on your device to determine your location. You can
                  also try again.
                </Text>
              ) : null}
            </Flex>
          )}
        </Flex>
      ) : null}
    </Box>
  )
}

export default memo(FindLocationTab)
