// ui/src/lib/components/chart/PercentBarChart.svelte
<script lang="ts">
	import { Progress } from '$lib/components/ui/progress'
	import { formatPercent } from '$lib/util/format'
	import { cn } from '$lib/utils'

	const { label, percent, class: className = '' } = $props()
</script>

<div class={className}>
	<div
		class={cn('flex gap-4 justify-between flex-nowrap items-end opacity-50 leading-tight', {
			'opacity-100': percent > 0
		})}
	>
		<div class={cn('flex-auto text-grey', { 'text-foreground': percent > 0 })}>
			{label}
		</div>
		<div class="text-grey-8 flex-none text-sm">
			{formatPercent(percent)}% of area
		</div>
	</div>
	<Progress
		value={percent}
		max={100}
		class={cn('h-3 bg-grey-1 [&>div]:bg-grey-8 opacity-50', { 'opacity-100': percent > 0 })}
	/>
</div>

// ui/src/components/chart/PercentBarChart.jsx
/** @jsxRuntime classic */
/** @jsx jsx */

// eslint-disable-next-line no-unused-vars
import React from 'react'
import PropTypes from 'prop-types'

import { Box, Flex, Progress, Text, jsx } from 'theme-ui'

import { formatPercent } from 'util/format'

const PercentBarChart = ({ label, percent, color, ...props }) => (
  <Box {...props}>
    <Flex
      sx={{
        justifyContent: 'space-between',
        fontSize: 1,
        flexWrap: 'nowrap',
        alignItems: 'flex-end',
        opacity: percent > 0 ? 1 : 0.5,
      }}
    >
      <Text
        sx={{
          flex: '1 1 auto',
          mr: '1em',
          color: percent > 0 ? 'inherit' : 'grey.8',
        }}
      >
        {label}
      </Text>
      <Text sx={{ color: 'grey.8', flex: '0 0 auto', fontSize: 0 }}>
        {formatPercent(percent)}% of area
      </Text>
    </Flex>
    <Progress
      variant="styles.progress.percent"
      value={percent}
      max={100}
      color={color}
      sx={{ opacity: percent > 0 ? 1 : 0.5 }}
    />
  </Box>
)

PercentBarChart.propTypes = {
  label: PropTypes.string.isRequired,
  percent: PropTypes.number,
  color: PropTypes.string,
}

PercentBarChart.defaultProps = {
  color: 'grey.8',
  percent: 0,
}

export default PercentBarChart
