// ui/src/routes/custom_report/UploadForm.svelte
<script lang="ts">
	import { fromEvent as getFilesFromEvent } from 'file-selector'
	import { superForm, fileProxy, defaults, setError } from 'sveltekit-superforms'
	import { zodClient } from 'sveltekit-superforms/adapters'
	import { zod } from 'sveltekit-superforms/adapters'
	import { z } from 'zod'

	import Download from '~icons/fa-solid/download'
	import ExclamationTriangle from '~icons/fa-solid/exclamation-triangle'
	import { cn } from '$lib/utils.js'
	import { Field, Control, Label, Button as SubmitButton } from '$lib/components/ui/form'
	import { Button } from '$lib/components/ui/button'
	import { Input } from '$lib/components/ui/input'
	import { ContactDialog } from '$lib/components/dialog'

	const MAXSIZE_MB = 100
	const MIME_TYPES = new Set([
		'application/zip',
		'application/x-zip-compressed',
		'application/x-compressed',
		'multipart/x-zip'
	])

	const { onSubmit } = $props()
	let isDragValid: boolean | null = $state(null)

	const schema = z.object({
		areaName: z.string().optional(),
		file: z
			.instanceof(File, {
				message: 'Please select a file'
			})
			.refine((f) => f.size < MAXSIZE_MB * 1e6, `File must be less than ${MAXSIZE_MB} MB`)
			.refine(({ type: mimeType }) => MIME_TYPES.has(mimeType), 'File must be a ZIP file')
	})

	const form = superForm(defaults(zod(schema)), {
		SPA: true,
		validators: zodClient(schema),
		onUpdate: function ({ form }) {
			const {
				valid,
				data: { areaName = '', file }
			} = form

			if (!valid) {
				return
			}

			onSubmit(areaName, file)
		}
	})

	const { form: formData, submitting, delayed, enhance, errors, validate } = form
	const fileHandle = fileProxy(formData, 'file')

	const handleDragOver = async (e: DragEvent) => {
		e.preventDefault()
		e.stopPropagation()

		const hasFiles =
			e.dataTransfer &&
			Array.prototype.some.call(
				e.dataTransfer.types,
				(type) => type === 'Files' || type === 'application/x-moz-file'
			)

		if (hasFiles) {
			const files = await getFilesFromEvent(e)
			const [file] = files
			// cannot check file size here, it isn't always defined on file
			isDragValid = files.length === 1 && MIME_TYPES.has(file.type)
		}
	}

	const handleDragOut = (e: DragEvent) => {
		e.preventDefault()
		isDragValid = null
	}

	const handleDrop = async (e: DragEvent) => {
		e.preventDefault()
		isDragValid = null

		const hasFiles =
			e.dataTransfer &&
			Array.prototype.some.call(
				e.dataTransfer.types,
				(type) => type === 'Files' || type === 'application/x-moz-file'
			)

		if (hasFiles) {
			const files = await getFilesFromEvent(e)
			const [file] = files

			if (files.length > 1) {
				alert('Multiple files not allowed')
				return
			}

			fileHandle.set(file as File)
			await validate('file')
		}
	}

	const handleResetFile = async () => {
		form.reset({
			newState: {
				areaName: $formData.areaName
			}
		})
	}

	const isFileValid = $derived($formData.file && !$errors.file)
	const isValid = $derived(isFileValid && !$errors.areaName)
</script>

<div class="container text-lg pt-12 pb-16 leading-snug">
	<div class="grid grid-cols-2 gap-16">
		<div>
			<form enctype="multipart/form-data" use:enhance>
				<Field {form} name="areaName">
					<Control>
						{#snippet children({ props })}
							<Label for="areaName" class="text-2xl font-bold">Area Name (optional):</Label>
							<Input {...props} bind:value={$formData.areaName} class="mt-2" />
						{/snippet}
					</Control>
				</Field>

				<Field {form} name="file" class="mt-12">
					<Control>
						{#snippet children({ props })}
							<Label
								for="file"
								class="block"
								ondragover={handleDragOver}
								ondrop={handleDrop}
								ondragleave={handleDragOut}
							>
								<div class="text-2xl font-bold">Choose Area of Interest:</div>
								<Input
									type="file"
									{...props}
									bind:files={$fileHandle}
									accept={[...MIME_TYPES].join(',')}
									multiple={false}
									class="mt-2 hidden"
								/>

								<div
									class={cn(
										'border-2 border-grey-5 rounded-lg bg-grey-1/40 border-dashed p-6 flex flex-col justify-center items-center text-center cursor-pointer mt-2',
										{
											'border-error': isDragValid === false || $errors.file,
											'bg-error/10': isDragValid === false || $errors.file,
											'cursor-not-allowed': isDragValid === false,
											'border-ok': isDragValid === true,
											'bg-ok/10': isDragValid === true,
											hidden: isFileValid
										}
									)}
								>
									<div>
										<Download width="2rem" height="2rem" />
									</div>
									<p class="text-2xl font-bold mt-2">Drop your zip file here</p>
									<p class="text-lg text-grey-8 leading-tight mt-4">
										Zip file must contain all associated files for a shapefile (at least .shp, .prj,
										.shx) <br />or file geodatabase (.gdb).
										<br />
										<br />
										Max size: {MAXSIZE_MB} MB.
									</p>
								</div>

								{#if isFileValid}
									<div class="text-lg ml-4">
										Selected: {$formData.file.name}
									</div>
								{/if}
							</Label>

							{#if $errors.file}
								<div class="flex items-center gap-2 text-accent ml-2 mt-4 mb-8">
									<ExclamationTriangle width="1em" height="1em" />
									{$errors.file}
								</div>
							{/if}
						{/snippet}
					</Control>
					<p class="text-sm text-grey-8 mx-4">
						Note: your files must be in a zip file, and can include only one shapefile or Feature
						Class, and should represent a relatively small area. For help analyzing larger areas,
						please <ContactDialog>
							<span class="text-link hover:underline cursor-pointer"> contact us</span>
						</ContactDialog>.
					</p>
				</Field>

				<div class="flex justify-between border-t border-t-grey-2 pt-8 mt-8">
					<div>
						{#if isFileValid}
							<Button onclick={handleResetFile} variant="secondary" class="text-xl"
								>Choose a different file</Button
							>
						{/if}
					</div>
					<SubmitButton disabled={!isValid} class="text-xl">Create Report</SubmitButton>
				</div>
			</form>
		</div>
		<div>
			<p>
				Upload a zipped shapefile or ESRI File Geodatabase Feature Class containing your area of
				interest to generate a detailed PDF report of the Blueprint, underlying indicators, and
				other contextual information for your area of interest. It includes a map and summary table
				for every indicator present in the area, as well as additional information about
				urbanization and sea-level rise.
				<br />
				<br />
				Don&apos;t have a shapefile? You can create one using{' '}
				<a href="https://geojson.io/#map=6/32.861/-81.519" target="_blank"> geojson.io </a>{' '}
				to draw your area of interest, save as a shapefile, then upload here.
				<br />
				<br />
				<ContactDialog>
					<span class="text-link hover:underline cursor-pointer">We are here</span>
				</ContactDialog>{' '}
				to help you interpret and apply this information to your particular application!
				<br />
				<br />
				We are working on resolving some technical challenges to make these these automatically generated
				reports more accessible to people with disabilities. In the meantime, to request an accessible
				PDF or other assistance, please contact Hilary Morris at{' '}
				<a href="mailto:hilary_morris@fws.gov"> hilary_morris@fws.gov </a>.
				<br />
				<br />
				You can help us improve the Blueprint and this report by helping us understand your use case:
				we use this information to provide statistics about how the Blueprint is being used and to prioritize
				improvements.
			</p>
		</div>
	</div>

	<hr />

	<h3 class="text-2xl">Examples of what is inside</h3>

	<div class="grid grid-cols-2 md:grid-cols-5 mt-2 gap-4 [&_img]:border [&_img]:border-grey-2">
		<enhanced:img src="$images/report/report_sm_1.png" alt="Tool report example screenshot 1" />
		<enhanced:img src="$images/report/report_sm_2.png" alt="Tool report example screenshot 2" />
		<enhanced:img src="$images/report/report_sm_3.png" alt="Tool report example screenshot 3" />
		<enhanced:img src="$images/report/report_sm_4.png" alt="Tool report example screenshot 4" />
		<enhanced:img src="$images/report/report_sm_5.png" alt="Tool report example screenshot 5" />
	</div>
	<p class="mt-2 text-lg">...and much more!</p>
</div>

// ui/src/components/report/UploadForm.jsx
import React, { useCallback } from 'react'
import PropTypes from 'prop-types'
import {
  Box,
  Button,
  Flex,
  Heading,
  Label,
  Input,
  Text,
  Divider,
  Grid,
  Image,
  Paragraph,
} from 'theme-ui'
import { FormProvider, useForm } from 'react-hook-form'

import { ContactModal } from 'components/modal'
import { OutboundLink } from 'components/link'

import Thumbnail1 from 'images/report/report_sm_1.png'
import Thumbnail2 from 'images/report/report_sm_2.png'
import Thumbnail3 from 'images/report/report_sm_3.png'
import Thumbnail4 from 'images/report/report_sm_4.png'
import Thumbnail5 from 'images/report/report_sm_5.png'

import DropZone from './DropZone'

const linkCSS = {
  display: 'inline-block',
  color: 'link',
  cursor: 'pointer',
  '&:hover': { textDecoration: 'underline' },
}

const UploadForm = ({ onFileChange, onCreateReport }) => {
  const methods = useForm({
    mode: 'onBlur',
  })

  const {
    formState: { isValid },
    register,
    watch,
    setValue,
  } = methods

  const file = watch('file', null)

  const handleSubmit = useCallback(
    (values) => {
      const { areaName, file: fileProp } = values

      onCreateReport(fileProp, areaName)
    },
    [onCreateReport]
  )

  const handleResetFile = () => {
    setValue('file', null)
    onFileChange()
  }

  return (
    <>
      <FormProvider {...methods}>
        <form onSubmit={methods.handleSubmit(handleSubmit)}>
          <Grid columns={[0, 2]} gap={5} sx={{ mt: '2rem' }}>
            <Box>
              <Box>
                <Label
                  htmlFor="areaName"
                  sx={{ mb: '0.5rem', fontWeight: 'bold', fontSize: [3, 4] }}
                >
                  Area Name (optional):
                </Label>
                <Input
                  type="text"
                  id="areaName"
                  name="areaName"
                  {...register('areaName', { required: false })}
                />
              </Box>

              <Flex
                sx={{
                  mt: '2rem',
                  mb: '0.5em',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div>
                  <Label
                    htmlFor="file"
                    sx={{
                      mb: 0,
                      fontWeight: 'bold',
                      fontSize: [3, 4],
                    }}
                  >
                    Choose Area of Interest:
                  </Label>
                  <div>{file && <Text>{file.name}</Text>}</div>
                </div>
              </Flex>

              <Box sx={{ display: file ? 'none' : 'block' }}>
                <DropZone name="file" id="file" />
              </Box>

              <Box
                sx={{ fontSize: 0, color: 'grey.8', px: '1rem', mt: '0.5rem' }}
              >
                Note: your files must be in a zip file, and can include only one
                shapefile or Feature Class, and must represent a relatively
                small area (full extent must be less than 5 million acres). For
                help analyzing larger areas, please{' '}
                <ContactModal>
                  <Text sx={linkCSS}>contact us</Text>
                </ContactModal>
                .
              </Box>
              <Divider />
              <Flex
                sx={{
                  justifyContent: 'space-between',
                }}
              >
                <Button
                  variant="secondary"
                  onClick={handleResetFile}
                  sx={{ visibility: file ? 'visible' : 'hidden' }}
                >
                  Choose a different file
                </Button>

                <Button
                  as="button"
                  type="submit"
                  variant={isValid ? 'primary' : 'disabled'}
                  disabled={!isValid}
                >
                  Create Report
                </Button>
              </Flex>
            </Box>

            <Paragraph>
              Upload a zipped shapefile or ESRI File Geodatabase Feature Class
              containing your area of interest to generate a detailed PDF report
              of the Blueprint, underlying indicators, and landscape-level
              threats for your area of interest. It includes a map and summary
              table for every indicator present in the area, as well as
              additional information about urbanization and sea-level rise.
              <br />
              <br />
              Don&apos;t have a shapefile? You can create one using{' '}
              <OutboundLink to="https://geojson.io/#map=6/32.861/-81.519">
                geojson.io
              </OutboundLink>{' '}
              to draw your area of interest, save as a shapefile, then upload
              here.
              <br />
              <br />
              <ContactModal>
                <Text sx={linkCSS}>
                  <b>We are here</b>
                </Text>
              </ContactModal>{' '}
              to help you interpret and apply this information to your
              particular application!
              <br />
              <br />
              We are working on resolving some technical challenges to make
              these these automatically generated reports more accessible to
              people with disabilities. In the meantime, to request an
              accessible PDF or other assistance, please contact Hilary Morris
              at{' '}
              <a href="mailto:hilary_morris@fws.gov">hilary_morris@fws.gov</a>.
              <br />
              <br />
              You can help us improve the Blueprint and this report by helping
              us understand your use case: we use this information to provide
              statistics about how the Blueprint is being used and to prioritize
              improvements.
            </Paragraph>
          </Grid>
        </form>
      </FormProvider>

      <Box
        sx={{
          mt: '2rem',
          borderTop: '1px solid',
          borderTopColor: 'grey.3',
          pt: '2rem',
          mb: '4rem',
        }}
      >
        <Heading as="h3">Examples of what is inside</Heading>
        <Grid
          columns={5}
          sx={{
            mt: '1rem',
            img: {
              width: '250px',
              border: '1px solid',
              borderColor: 'grey.4',
              boxShadow: `1px 1px 3px #000`,
            },
          }}
        >
          <Image src={Thumbnail1} alt="Tool report example screenshot 1" />
          <Image src={Thumbnail2} alt="Tool report example screenshot 2" />
          <Image src={Thumbnail3} alt="Tool report example screenshot 3" />
          <Image src={Thumbnail4} alt="Tool report example screenshot 4" />
          <Image src={Thumbnail5} alt="Tool report example screenshot 5" />
        </Grid>
        <Paragraph sx={{ mt: '1rem' }}>...and much more!</Paragraph>
      </Box>
    </>
  )
}

UploadForm.propTypes = {
  onFileChange: PropTypes.func.isRequired,
  onCreateReport: PropTypes.func.isRequired,
}

export default UploadForm
