// ui/src/lib/components/map/FindLocation.svelte
<script lang="ts">
	import CaretRightIcon from '~icons/fa-solid/caret-right'
	import CaretDownIcon from '~icons/fa-solid/caret-down'
	import { Button } from '$lib/components/ui/button'
	import { LatLon, Search } from '$lib/components/search'
	import { cn } from '$lib/utils'
	import type { LocationData } from '$lib/types'

	let placenameInputNode: HTMLInputElement | null = $state(null)
	let latLonInputNode: HTMLInputElement | null = $state(null)
	let showOptions: boolean = $state(false)
	let mode: string = $state('placename')
	let prevMode: string = $state('placename')
	let isFocused: boolean = $state(true)

	const toggleShowOptions = (e: Event) => {
		e.stopPropagation()
		showOptions = !showOptions
		isFocused = false
		mode = showOptions ? 'select-mode' : prevMode
	}

	const handlePlacenameSelect = () => {
		isFocused = false
	}

	const handlePlacenameFocus = () => {
		showOptions = false
		isFocused = true
	}

	const handleLatLonFocus = () => {
		showOptions = false
		isFocused = true
	}

	const setPlacenameMode = (e: Event) => {
		e.stopPropagation()
		placenameInputNode?.focus()

		mode = 'placename'
		prevMode = mode
		showOptions = false
		isFocused = true
	}

	const setLatLonMode = (e: Event) => {
		e.stopPropagation()
		latLonInputNode?.focus()

		mode = 'latlon'
		prevMode = mode
		showOptions = false
		isFocused = true
	}

	const handleWindowClick = () => {
		if (isFocused) {
			showOptions = false
			isFocused = false
		}
	}

	$effect(() => {
		if (!isFocused) {
			return
		}

		if (mode === 'placename') {
			placenameInputNode?.focus()
		} else if (mode === 'latlon') {
			latLonInputNode?.focus()
		}
	})
</script>

<svelte:document
	onclick={(e: Event) => {
		handleWindowClick()
	}}
/>

<div
	class={cn(
		'hidden md:block absolute p-[6px] text-grey-9 bg-white pointer-events-auto rounded-[0.25rem] border-2 border-grey-2 shadow-md shadow-grey-5 user-select-none z-[2001] top-0 right-0 w-[150px]',
		{
			'w-[290px]': isFocused || showOptions
		}
	)}
>
	<div class="flex gap-0 items-start">
		<Button
			class="flex-none text-grey-8 bg-white p-0 w-4 h-8 border-none shadow-none hover:bg-white"
			onclick={toggleShowOptions}
		>
			{#if showOptions}
				<CaretDownIcon class="size-7 mt-1" />
			{:else}
				<CaretRightIcon class="size-7 mt-1" />
			{/if}
		</Button>
		<div class="flex-auto">
			{#if mode === 'placename'}
				<div class="[&_.search-results]:-ml-7">
					<Search
						bind:ref={placenameInputNode}
						isCompact={!isFocused}
						onFocus={handlePlacenameFocus}
						onSelect={handlePlacenameSelect}
					/>
				</div>
			{:else if mode === 'latlon'}
				<LatLon bind:ref={latLonInputNode} isCompact={!isFocused} onFocus={handleLatLonFocus} />
			{:else}
				<Button
					class="flex-none text-md mt-0.5 text-grey-8 bg-white p-0 h-8 border-none shadow-none hover:bg-white"
					onclick={toggleShowOptions}>Select one of the following:</Button
				>
			{/if}
		</div>
	</div>

	{#if showOptions}
		<div class="mt-1 pt-1 border-t border-t-grey-3 leading-none">
			<Button
				onclick={setPlacenameMode}
				class="text-md bg-white hover:bg-grey-0 text-foreground h-8 w-full shadow-none justify-start"
			>
				Find by a name or address
			</Button>
			<Button
				onclick={setLatLonMode}
				class="text-md bg-white hover:bg-grey-0 text-foreground h-8 w-full shadow-none justify-start mt-[2px]"
				>Find by latitude & longitude</Button
			>
		</div>
	{/if}
</div>

// ui/src/components/map/FindLocation.jsx
import React, {
  useCallback,
  useState,
  useEffect,
  useLayoutEffect,
  useRef,
} from 'react'
import { CaretRight, CaretDown } from '@emotion-icons/fa-solid'
import { Box, Flex } from 'theme-ui'

import { Search, LatLon } from 'components/search'
import { hasWindow } from 'util/dom'

const controlCSS = {
  alignItems: 'center',
  justifyContent: 'center',
  position: 'absolute',
  padding: '6px',
  color: 'grey.9',
  bg: '#FFF',
  pointerEvents: 'auto',
  borderRadius: '0.25rem',
  boxShadow: '0 0 0 2px rgba(0,0,0,.1)',
}

const FindLocation = () => {
  const placenameInputRef = useRef()
  const latLonInputRef = useRef(null)
  const isMountedRef = useRef(false)

  const [{ showOptions, showPlacenameResults, mode, isFocused }, setState] =
    useState({
      showOptions: false,
      showPlacenameResults: true,
      mode: 'placename',
      isFocused: false,
    })

  const toggleShowOptions = useCallback((e) => {
    e.stopPropagation()

    setState(({ showOptions: prevShowOptions, ...prevState }) => ({
      ...prevState,
      showOptions: !prevShowOptions,
      showPlacenameResults: false,
      isFocused: true,
    }))
  }, [])

  const handlePlacenameSelect = useCallback(() => {
    setState((prevState) => ({
      ...prevState,
      showPlacenameResults: false,
      isFocused: false,
    }))
  }, [])

  const handlePlacenameFocus = useCallback(() => {
    setState((prevState) => ({
      ...prevState,
      showOptions: false,
      showPlacenameResults: true,
      isFocused: true,
    }))
  }, [])

  const handleLatLonFocus = useCallback(() => {
    setState((prevState) => ({
      ...prevState,
      showOptions: false,
      isFocused: true,
    }))
  }, [])

  const setPlacenameMode = useCallback((e) => {
    e.stopPropagation()

    if (placenameInputRef.current) {
      placenameInputRef.current.focus()
    }

    setState(({ mode: prevMode, ...prevState }) => ({
      ...prevState,
      mode: 'placename',
      showOptions: false,
      showPlacenameResults: true,
      isFocused: true,
    }))
  }, [])

  const setLatLonMode = useCallback((e) => {
    e.stopPropagation()

    if (latLonInputRef.current) {
      latLonInputRef.current.focus()
    }

    setState((prevState) => ({
      ...prevState,
      mode: 'latlon',
      showOptions: false,
      isFocused: true,
    }))
  }, [])

  useLayoutEffect(() => {
    // skip on first mount
    if (!isMountedRef.current) {
      isMountedRef.current = true
      return
    }

    if (mode === 'placename') {
      if (placenameInputRef.current) {
        placenameInputRef.current.focus()
      }
    } else if (latLonInputRef.current) {
      latLonInputRef.current.focus()
    }
  }, [mode])

  // prevent click from calling window click handler
  const handleClick = useCallback((e) => e.stopPropagation(), [])

  // add event listener to the window
  useEffect(() => {
    const handleWindowClick = () => {
      if (isFocused) {
        setState((prevState) => ({
          ...prevState,
          showOptions: false,
          showPlacenameResults: false,
          isFocused: false,
        }))
      }
    }

    if (hasWindow) {
      document.addEventListener('click', handleWindowClick)
    }

    return () => {
      if (hasWindow) {
        document.removeEventListener('click', handleWindowClick)
      }
    }
  }, [isFocused])

  return (
    <>
      <Box
        onClick={handleClick}
        sx={{
          ...controlCSS,
          zIndex: 20001,
          top: '10px',
          right: '10px',
          overflow: 'hidden',
          userSelect: 'none',
          width: isFocused || showOptions ? '290px' : '160px',
        }}
      >
        <Flex sx={{ alignItems: 'flex-start' }}>
          <Box
            onClick={toggleShowOptions}
            sx={{ flex: '0 0 auto', cursor: 'pointer', color: 'grey.8' }}
          >
            {showOptions ? (
              <CaretDown size="1.5em" />
            ) : (
              <CaretRight size="1.5em" style={{ marginTop: '0.2rem' }} />
            )}
          </Box>
          <Box sx={{ flex: '1 1 auto', fontSize: 0 }}>
            <Box
              sx={{
                display: mode === 'placename' ? 'block' : 'none',
                '& .search-results': {
                  mt: '0.5rem',
                  ml: '-1.5rem',
                  display: showPlacenameResults ? 'block' : 'none',
                },
              }}
            >
              <Search
                ref={placenameInputRef}
                onFocus={handlePlacenameFocus}
                onSelect={handlePlacenameSelect}
              />
            </Box>

            <Box
              sx={{
                display: mode === 'latlon' ? 'block' : 'none',
              }}
            >
              <LatLon
                ref={latLonInputRef}
                isCompact={!isFocused}
                onFocus={handleLatLonFocus}
              />
            </Box>
          </Box>
        </Flex>

        {showOptions ? (
          <Box
            sx={{
              mt: '0.25rem',
              pt: '0.25rem',
              borderTop: '1px solid',
              borderTopColor: 'grey.3',
              fontSize: 1,
              lineHeight: 1,
              '& > div': {
                p: '0.25rem',
                cursor: 'pointer',
                '&:hover': {
                  bg: 'grey.0',
                },
              },
            }}
          >
            <Box onClick={setPlacenameMode}>Find by a name or address</Box>
            <Box onClick={setLatLonMode}>Find by latitude & longitude</Box>
          </Box>
        ) : null}
      </Box>
    </>
  )
}

// TODO: memo?
export default FindLocation
