// ui/src/lib/components/map/Map.svelte
<script lang="ts">
	import { getContext, untrack } from 'svelte'
	import { MapboxOverlay } from '@deck.gl/mapbox'

	import CrosshairsIcon from '$images/CrosshairsIcon.svg'
	import Spinner from '~icons/fa-solid/spinner'

	import {
		ecosystems as ecosystemInfo,
		indicators as indicatorInfo,
		subregionIndex
	} from '$lib/config/constants'
	import { mapConfig as config, sources, layers } from '$lib/config/map'
	import { pixelLayers, renderLayersIndex } from '$lib/config/pixelLayers'
	import type { MapData } from '$lib/components/map'
	import type { LocationData, PixelLayer } from '$lib/types'
	import { indexBy } from '$lib/util/data'
	import { debounce, eventHandler } from '$lib/util/func'

	import { unpackFeatureData } from './features'
	import FindLocation from './FindLocation.svelte'
	import { extractPixelData, StackedPNGTileLayer } from './gl'
	import { Legend } from './legend'

	import LayerToggle from './LayerToggle.svelte'
	import { mapboxgl } from './mapbox'
	import { ModeToggle } from './mode'
	import StyleToggle from './StyleToggle.svelte'
	import { getCenterAndZoom } from './viewport'

	let map: mapboxgl.Map
	let marker: mapboxgl.Marker | null = null

	const mapData: MapData = getContext('map-data')
	const locationData: LocationData = getContext('location-data')

	let isLoaded: boolean = $state(false)
	let isRenderLayerVisible: boolean = $state(true)
	let currentZoom: number = $state(3)
	let highlightId: number | string | undefined = $state()
	let renderLayer: PixelLayer = $state.raw(renderLayersIndex.blueprint)

	// mapIsDrawing is used to show the spinner; it only gets set via a deounced callback to prevent short duration flashes
	let mapIsDrawing: boolean = $state(false)
	// delayedMapIsDrawing is toggled immediately when map enters drawing state and is used in callback to determine if should toggle mapIsDrawing
	let delayedMapIsDrawing: boolean = $state(false)

	const deckGLHandler = eventHandler(50)
	const updateMapIsDrawing = debounce(() => {
		mapIsDrawing = delayedMapIsDrawing
	}, 1500)

	// resize map to handle layout shift on mobile
	const resizeMap = debounce(() => {
		map.resize()
	}, 10)

	// layer in Mapbox Light that we want to come AFTER our layers here
	const beforeLayer = 'waterway-label'

	const minPixelLayerZoom = 7 // minimum reasonable zoom for getting pixel data
	const minSummaryZoom = layers.filter(({ id }) => id === 'unit-outline')[0].minzoom

	const setPixelLayerProps = (newProps) => {
		if (!map) return

		// this happens in hot reload
		if (!(map && map.__deck && map.__deck.layerManager)) return

		/* eslint-disable-next-line no-underscore-dangle */
		map.__deck.setProps({
			layers: [
				/* eslint-disable-next-line no-underscore-dangle */
				map.__deck.layerManager.layers[0].clone(newProps)
			]
		})
	}

	const getPixelData = debounce(() => {
		if (mapData.mapMode !== 'pixel' || !map) {
			return
		}

		if (currentZoom < minPixelLayerZoom) {
			mapData.setData(null)
			resizeMap()
			return
		}

		const layer = map.getLayer('pixelLayers')
		// don't fetch data if layer is not yet available or is not visible
		if (!(layer && layer.deck && layer.deck.layerManager.layers[0].props.visible)) {
			return
		}

		const { lng: longitude, lat: latitude } = map.getCenter()

		// If protected areas tiles aren't loaded yet, schedule a callback once tiles are loaded
		if (
			!(
				map.style._otherSourceCaches.protectedAreas &&
				map.style._otherSourceCaches.protectedAreas.loaded()
			)
		) {
			mapData.setData({
				type: 'pixel',
				location: {
					longitude,
					latitude
				},
				isLoading: true
			})
			resizeMap()
			map.once('idle', () => {
				getPixelData()
			})
		}

		const pixelData = extractPixelData(map, map.getCenter(), layer, ecosystemInfo, indicatorInfo)

		if (pixelData === null) {
			// tile data not yet loaded for correct zoom, try again after next deckGL
			// render pass
			deckGLHandler.once(() => {
				getPixelData()
			})
		}

		mapData.setData({
			type: 'pixel',
			location: {
				longitude,
				latitude
			},
			isLoading: pixelData === null,
			...(pixelData || {})
		})
		resizeMap()
	}, 10)

	const updateVisibleSubregions = debounce(() => {
		if (mapData.mapMode !== 'filter' || !map) {
			return
		}

		const subregions = map
			// @ts-ignore
			.queryRenderedFeatures(null, { layers: ['subregions'] })
			// @ts-ignore
			.map(({ properties: { subregion } }) => subregion)

		mapData.visibleSubregions = new Set(subregions)
	}, 10)

	// use a callback to actually update the layers, since may style may still
	// be loading
	const updateVisibleLayers = () => {
		mapIsDrawing = true

		const isVisible = isRenderLayerVisible
		const pixelLayer = map.getLayer('pixelLayers')

		// toggle layer visibility
		if (mapData.mapMode === 'unit') {
			map.setLayoutProperty('unit-fill', 'visibility', 'visible')
			map.setLayoutProperty('unit-outline', 'visibility', 'visible')
			map.setLayoutProperty('blueprint', 'visibility', isVisible ? 'visible' : 'none')
			map.setLayoutProperty('protectedAreas', 'visibility', 'none')
			map.setLayoutProperty('subregions', 'visibility', 'none')

			// disable pixel layer event listener
			// @ts-ignore
			pixelLayer!.deck!.setProps({
				onAfterRender: () => {} // no-op
			})
			setPixelLayerProps({
				visible: false,
				filters: null, // reset filters (also reset in parent state)
				data: { visible: false }
			})

			updateMapIsDrawing()

			return
		}
		// pixel identify / filter modes
		else if (mapData.mapMode === 'pixel') {
			// enable pixel layer event listener
			// @ts-ignore
			pixelLayer!.deck!.setProps({
				onAfterRender: deckGLHandler.handler
			})

			// immediately try to retrieve pixel data if in pixel mode
			if (map.getZoom() >= minPixelLayerZoom) {
				map.once('idle', () => {
					getPixelData()
				})
			}
		} else if (mapData.mapMode === 'filter') {
			// disable pixel layer event listener
			// @ts-ignore
			pixelLayer!.deck!.setProps({
				onAfterRender: () => {} // no-op
			})
		}

		map.setLayoutProperty('unit-fill', 'visibility', 'none')
		map.setLayoutProperty('unit-outline', 'visibility', 'none')
		// reset selected outline
		map.setFilter('unit-outline-highlight', ['==', 'id', Infinity])
		map.setLayoutProperty('blueprint', 'visibility', 'none')
		map.setLayoutProperty('protectedAreas', 'visibility', 'visible')
		map.setLayoutProperty('subregions', 'visibility', 'visible')

		if (mapData.mapMode === 'filter') {
			map.once('idle', () => {
				updateVisibleSubregions()
			})
		}

		setPixelLayerProps({
			visible: true,
			filters: mapData.activeFilterValues,
			// have to use opacity to hide so that pixel mode still works when hidden
			opacity: isVisible ? 0.7 : 0,
			// data prop is used to force loading of tiles if they aren't already loaded
			data: { visible: true }
		})

		updateMapIsDrawing()
	}

	const hideGulfOfMexico = () => {
		if (map === null) {
			return
		}
		// hide Gulf of Mexico
		if (map.style._layers['marine-label-md-pt']) {
			map.setFilter('marine-label-md-pt', [
				'all',
				['==', '$type', 'Point'],
				['in', 'labelrank', 2, 3],
				['!=', 'name', 'Gulf of Mexico']
			])
		} else if (map.style._layers['water-point-label']) {
			map.setFilter('water-point-label', [
				'all',
				[
					'match',
					['get', 'class'],
					// remove 'sea'; this category includes the gulf
					['ocean', 'reservoir', 'water'],
					true,
					false
				],
				['==', ['geometry-type'], 'Point']
			])
		}
	}

	const createMap = (mapNode: HTMLDivElement) => {
		const { bounds, maxBounds, minZoom, maxZoom } = config
		const { center, zoom } = getCenterAndZoom(mapNode, bounds, 0)

		map = new mapboxgl.Map({
			container: mapNode,
			style: 'mapbox://styles/mapbox/light-v9',
			center,
			zoom,
			minZoom,
			maxZoom,
			maxBounds
		})

		// @ts-ignore
		window.map = map // for easier debugging and querying via console

		map.addControl(new mapboxgl.NavigationControl(), 'top-right')

		map.on('style.load', hideGulfOfMexico)

		map.on('load', () => {
			// add sources
			Object.entries(sources).forEach(([id, source]) => {
				// @ts-ignore
				map.addSource(id, source)
			})

			// add DeckGL pixel layer
			// by default, renders the blueprint
			const deckGLOverlay = new MapboxOverlay({
				interleaved: true,

				layers: [
					new StackedPNGTileLayer({
						id: 'pixelLayers',
						interleaved: true,
						beforeId: beforeLayer,
						refinementStrategy: 'no-overlap',
						debounceTime: 10, // slightly debounce tile requests during major zoom / pan events
						layers: pixelLayers,
						extent: bounds,
						maxRequests: 20, // because these are on HTTP/2, we can fetch many at once
						opacity: 0.7,
						filters: null,
						visible: false,
						renderLayer,
						tileSize: 512,
						useWebGL2: true
					})
				]
			})
			map.addControl(deckGLOverlay)

			map.once('idle', () => {
				// update state once to trigger other components to update with map object
				isLoaded = true
			})

			// add normal mapbox layers// add layers
			layers.forEach((layer) => {
				// @ts-ignore
				map.addLayer(layer, beforeLayer)
			})

			// if map is initialized in pixel or filter mode
			if (mapData.mapMode === 'pixel' || mapData.mapMode === 'filter') {
				map.setLayoutProperty('unit-fill', 'visibility', 'none')
				map.setLayoutProperty('unit-outline', 'visibility', 'none')
				map.setLayoutProperty('blueprint', 'visibility', 'none')
				map.setLayoutProperty('protectedAreas', 'visibility', 'visible')
				map.setLayoutProperty('subregions', 'visibility', 'visible')

				map.once('idle', () => {
					setPixelLayerProps({
						visible: true,
						filters: null,
						data: { visible: true }
					})
					map.once('idle', () => {
						getPixelData()
					})
				})
			}

			// enable event listener for renderer
			if (mapData.mapMode === 'pixel') {
				// @ts-ignore
				map.getLayer('pixelLayers')!.deck!.setProps({
					onAfterRender: deckGLHandler.handler
				})
			} else if (mapData.mapMode === 'filter') {
				map.once('idle', () => {
					updateVisibleSubregions()
				})
			}

			currentZoom = map.getZoom()

			map.on('move', () => {
				if (mapData.mapMode === 'pixel') {
					getPixelData()
				}
			})

			map.on('moveend', () => {
				delayedMapIsDrawing = true
				if (mapData.mapMode === 'filter') {
					updateVisibleSubregions()
				}
				updateMapIsDrawing()
			})

			map.on('zoomend', () => {
				if (mapData.mapMode === 'pixel') {
					getPixelData()
				} else if (mapData.mapMode === 'filter') {
					updateVisibleSubregions()
				}
				currentZoom = map.getZoom()
			})
		})

		map.on('idle', () => {
			mapIsDrawing = false
			delayedMapIsDrawing = false
		})

		map.on('click', ({ lngLat: point }) => {
			if (mapData.mapMode === 'pixel') {
				return
			}

			const features = map.queryRenderedFeatures(map.project(point), {
				layers: ['unit-fill']
			})

			if (!(features && features.length > 0)) {
				mapData.setData(null)
				resizeMap()
				return
			}

			const { properties } = features[0]

			// highlight selected
			map.setFilter('unit-outline-highlight', ['==', 'id', properties!.id])

			mapData.setData(unpackFeatureData(properties, ecosystemInfo, indicatorInfo, subregionIndex))
			resizeMap()
		})

		// Highlight units on mouseover
		map.on('mousemove', 'unit-fill', ({ features }) => {
			if (!map.isStyleLoaded()) {
				return
			}

			map.getCanvas().style.cursor = 'pointer'

			if (!(features && features.length > 0)) {
				return
			}

			const { id } = features[0]

			if (highlightId !== undefined && highlightId !== id) {
				map.setFeatureState(
					// @ts-ignore
					{ source: 'mapUnits', sourceLayer: 'units', id: highlightId },
					{ highlight: false }
				)
			}
			// @ts-ignore
			map.setFeatureState({ source: 'mapUnits', sourceLayer: 'units', id }, { highlight: true })
			highlightId = id
		})

		// Unhighlight all hover features on mouseout
		map.on('mouseout', () => {
			if (!map.isStyleLoaded()) {
				return
			}

			if (highlightId !== undefined) {
				map.setFeatureState(
					// @ts-ignore
					{ source: 'mapUnits', sourceLayer: 'units', id: highlightId },
					{ highlight: false }
				)
			}
			highlightId = undefined
		})

		// when this component is destroyed, remove the map
		return () => {
			map?.remove()
		}
	}

	const handleToggleRenderLayerVisible = () => {
		if (!map) return
		isRenderLayerVisible = !isRenderLayerVisible
		if (mapData.mapMode === 'unit') {
			map.setLayoutProperty('blueprint', 'visibility', isRenderLayerVisible ? 'visible' : 'none')
		} else {
			// have to toggle opacity not visibility so that pixel-level identify
			// still works
			setPixelLayerProps({ opacity: isRenderLayerVisible ? 0.7 : 0 })
		}
	}

	const handleBasemapChange = (styleID: string) => {
		if (!(map && isLoaded)) {
			return
		}

		const updateStyle = () => {
			const pixelLayer = map!.getLayer('pixelLayers')

			map!.setStyle(`mapbox://styles/mapbox/${styleID}`)

			map!.once('style.load', () => {
				hideGulfOfMexico()

				const {
					sources: styleSources,
					layers: styleLayers,
					// @ts-ignore
					metadata: { 'mapbox:origin': curStyleId }
				} = map!.getStyle()
				const layerIndex = indexBy(styleLayers, 'id')

				if (curStyleId === 'satellite-streets-v11') {
					// make satellite a bit more washed out
					map!.setPaintProperty('background', 'background-color', '#FFF')
					map!.setPaintProperty('satellite', 'raster-opacity', 0.75)
				}

				// add sources back
				Object.entries(sources).forEach(([id, source]) => {
					// make sure we're not trying to reload the same style, which already has these
					if (!styleSources[id]) {
						// @ts-ignore
						map!.addSource(id, source)
					}
				})

				// add regular layers and reapply filters / visibility
				layers.forEach((l) => {
					// make sure we're not trying to reload the same layers
					if (layerIndex[l.id]) {
						return
					}

					const layer = { ...l }

					if (mapData.mapMode !== 'unit') {
						if (l.id === 'blueprint' || l.id === 'unit-fill' || l.id === 'unit-outline') {
							layer.layout = {
								visibility: 'none'
							}
						}
						if (l.id === 'protectedAreas' || l.id === 'subregions') {
							layer.layout = {
								visibility: 'visible'
							}
						}
					} else {
						if (l.id === 'blueprint' && !isRenderLayerVisible) {
							layer.layout = {
								visibility: 'none'
							}
						}
						if (l.id === 'unit-outline-highlight' && mapData.data !== null) {
							// re-highlight selected layer
							layer.filter = ['==', 'id', mapData.data.id]
						}
					}

					// @ts-ignore
					map!.addLayer(layer, beforeLayer)
				})

				if (!map!.getLayer('pixelLayers')) {
					// pixel layer appears to now be retained on style change
					// @ts-ignore
					map!.addLayer(pixelLayer, beforeLayer)
				}
			})
		}

		// wait for previous to finish loading, if necessary
		if (map.isStyleLoaded()) {
			updateStyle()
		} else {
			map.once('idle', updateStyle)
		}
	}

	const handleSetRenderLayer = (newRenderLayer: PixelLayer) => {
		renderLayer = newRenderLayer
		setPixelLayerProps({ renderLayer: $state.snapshot(renderLayer) })
	}

	// effect for setting a location
	$effect(() => {
		locationData.location

		if (!untrack(() => isLoaded)) {
			return
		}

		if (locationData.location !== null) {
			const {
				location: { latitude, longitude }
			} = locationData
			map.jumpTo({ center: [longitude, latitude], zoom: 12 })
			if (!marker) {
				marker = new mapboxgl.Marker().setLngLat([longitude, latitude]).addTo(map)
			} else {
				marker?.setLngLat([longitude, latitude])
			}
		} else {
			marker?.remove()
			marker = null
		}
	})

	// effect for updates to mapMode
	$effect(() => {
		mapData.mapMode

		if (!untrack(() => isLoaded)) {
			return
		}

		if (!map.isStyleLoaded()) {
			map.once('idle', () => {
				updateVisibleLayers()
			})

			// stop any transitions underway
			map.stop()

			return
		}

		// stop any transitions underway
		map.stop()

		updateVisibleLayers()
	})

	// effect for changed mapData to reset boundary highlight
	$effect(() => {
		mapData.mapMode
		mapData.data

		if (!untrack(() => isLoaded)) {
			return
		}

		if (mapData.mapMode === 'unit' && mapData.data === null) {
			map.setFilter('unit-outline-highlight', ['==', 'id', Infinity])
		}
	})

	// effect for update to filters
	$effect(() => {
		// NOTE: have to specifically mark activeFilterValues to trigger this effect
		mapData.activeFilterValues

		if (!untrack(() => isLoaded)) {
			return
		}

		setPixelLayerProps({ filters: mapData.activeFilterValues })
	})

	const belowMinZoom = $derived(
		mapData.mapMode === 'pixel'
			? currentZoom < minPixelLayerZoom
			: currentZoom < (minSummaryZoom || 0)
	)

	const displayLayer = $derived(
		mapData.mapMode === 'unit' ? renderLayersIndex.blueprint : renderLayer
	)
</script>

<div class="h-full w-full flex-auto relative">
	<div class="h-full w-full" {@attach createMap}></div>

	{#if mapIsDrawing}
		<div
			class="absolute left-0 top-0 bottom-0 right-0 bg-grey-0/50 flex justify-center items-center"
		>
			<Spinner class="size-6 animate-spin" />
		</div>
	{/if}

	{#if mapData.mapMode === 'pixel' && currentZoom >= minPixelLayerZoom}
		<img
			src={CrosshairsIcon}
			alt="Crosshairs icon"
			class="absolute block z-0 right-0 bottom-0 left-[50%] top-[50%] ml-[-1rem] mt-[-1rem] pointer-events-none size-8"
		/>
	{/if}

	{#if isLoaded}
		<Legend
			title={displayLayer.label}
			subtitle={displayLayer.valueLabel}
			categories={displayLayer.categories}
			isVisible={isRenderLayerVisible}
			onToggleLayerVisibility={handleToggleRenderLayerVisible}
		/>

		{#if mapData.mapMode !== 'unit'}
			<LayerToggle {renderLayer} onSetRenderLayer={handleSetRenderLayer} />
		{/if}

		<FindLocation />

		<ModeToggle {belowMinZoom} />

		<StyleToggle onChange={handleBasemapChange} />
	{/if}
</div>

// ui/src/components/map/Map.jsx
// @refresh reset
/* eslint-disable no-underscore-dangle */

import React, { useEffect, useRef, useState, useCallback, memo } from 'react'
// exclude Mapbox GL from babel transpilation per https://docs.mapbox.com/mapbox-gl-js/guides/migrate-to-v2/
/* eslint-disable-next-line */
import mapboxgl from '!mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'
import { Box, Flex, Spinner } from 'theme-ui'
import { TileLayer } from '@deck.gl/geo-layers'
import { BitmapLayer } from '@deck.gl/layers'
import { MapboxOverlay } from '@deck.gl/mapbox'
import { useDebouncedCallback } from 'use-debounce'

import {
  ecosystems as ecosystemInfo,
  indicators as indicatorInfo,
  subregionIndex,
} from 'config'
import { useMapData } from 'components/data'
import { useBreakpoints } from 'components/layout'
import { useSearch } from 'components/search'
import { hasWindow, isLocalDev } from 'util/dom'
import { indexBy } from 'util/data'
import { useIsEqualEffect, useEventHandler } from 'util/hooks'
import CrosshairsIcon from 'images/CrosshairsIcon.svg'

import { unpackFeatureData } from './features'
import FindLocation from './FindLocation'
import { extractPixelData, StackedPNGTileLayer } from './gl'
import { mapConfig as config, sources, layers } from './mapConfig'
import { pixelLayers } from './pixelLayers'
import { Legend } from './legend'
import LayerToggle from './LayerToggle'
import MapModeToggle from './MapModeToggle'
import StyleToggle from './StyleToggle'
import { getCenterAndZoom } from './viewport'

import { siteMetadata } from '../../../gatsby-config'

const { mapboxToken, hidePixelLayerToggle } = siteMetadata

if (!mapboxToken) {
  // eslint-disable-next-line no-console
  console.error(
    'ERROR: Mapbox token is required in gatsby-config.js siteMetadata'
  )
}

// CSS props that control the responsive display of map widgets
const mapWidgetCSS = {
  '.mapboxgl-ctrl-zoom-in, .mapboxgl-ctrl-zoom-out, .mapboxgl-ctrl-compass': {
    display: ['none', 'inherit'],
  },
  '.mapboxgl-ctrl-attrib.mapboxgl-compact': {
    minHeight: '24px',
  },
  '.mapboxgl-ctrl-top-right': {
    top: '50px',
  },
}

// layer in Mapbox Light that we want to come AFTER our layers here
const beforeLayer = 'waterway-label'

const minPixelLayerZoom = 7 // minimum reasonable zoom for getting pixel data
const minSummaryZoom = layers.filter(({ id }) => id === 'unit-outline')[0]
  .minzoom

const setPixelLayerProps = (map, newProps) => {
  if (!map) return

  // this happens in hot reload
  if (!(map && map.__deck && map.__deck.layerManager)) return

  /* eslint-disable-next-line no-underscore-dangle */
  map.__deck.setProps({
    layers: [
      /* eslint-disable-next-line no-underscore-dangle */
      map.__deck.layerManager.layers[0].clone(newProps),
    ],
  })
}

const Map = () => {
  const mapNode = useRef(null)
  const mapRef = useRef(null)
  const {
    data: mapData,
    mapMode,
    setData: setMapData,
    renderLayer,
    filters,
    setVisibleSubregions,
  } = useMapData()
  const mapModeRef = useRef(mapMode)

  const [isLoaded, setIsLoaded] = useState(false)
  const [isRenderLayerVisible, setisRenderLayerVisible] = useState(true)
  const isRenderLayerVisibleRef = useRef(true) // ref is used in mapMode useEffect
  const filtersRef = useRef(null)
  const [currentZoom, setCurrentZoom] = useState(3)
  const highlightIDRef = useRef(null)
  const locationMarkerRef = useRef(null)
  const [mapIsDrawing, setMapIsDrawing] = useState(false)
  const mapIsDrawingRef = useRef(false)
  const deckGLHandler = useEventHandler(50)
  const breakpoint = useBreakpoints()
  const isMobile = breakpoint === 0
  const { location } = useSearch()

  const updateMapIsDrawing = useDebouncedCallback(() => {
    if (mapIsDrawingRef.current) {
      setMapIsDrawing(true)
    }
  }, 1500)

  const getPixelData = useDebouncedCallback(() => {
    // need to break out of pending events if the mode is different
    if (mapModeRef.current !== 'pixel') {
      return
    }
    const { current: map } = mapRef
    if (!map) return

    if (currentZoom < minPixelLayerZoom) {
      if (mapData !== null) {
        setMapData(null)
      }
      return
    }

    const layer = map.getLayer('pixelLayers')
    // don't fetch data if layer is not yet available or is not visible
    if (
      !(
        layer &&
        layer.implementation &&
        layer.implementation.deck &&
        layer.implementation.deck.layerManager.layers[0].props.visible
      )
    ) {
      return
    }

    const { lng: longitude, lat: latitude } = map.getCenter()

    // If ownership isn't loaded yet, schedule a callback once tiles are loaded
    if (
      !(
        map.style._otherSourceCaches.ownership &&
        map.style._otherSourceCaches.ownership.loaded()
      )
    ) {
      setMapData({
        type: 'pixel',
        location: {
          longitude,
          latitude,
        },
        isLoading: true,
      })
      map.once('idle', getPixelData)
    }

    const pixelData = extractPixelData(
      map,
      map.getCenter(),
      layer,
      ecosystemInfo,
      indicatorInfo
    )

    if (pixelData === null) {
      // tile data not yet loaded for correct zoom, try again after next deckGL
      // render pass
      deckGLHandler.once(() => {
        getPixelData()
      })
    }

    setMapData({
      type: 'pixel',
      location: {
        longitude,
        latitude,
      },
      isLoading: pixelData === null,
      ...(pixelData || {}),
    })
  }, 10)

  const updateVisibleSubregions = useDebouncedCallback(() => {
    if (mapModeRef.current !== 'filter') {
      return
    }

    const { current: map } = mapRef
    if (!map) return

    const subregions = map
      .queryRenderedFeatures(null, { layers: ['subregions'] })
      .map(({ properties: { subregion } }) => subregion)
    setVisibleSubregions(new Set(subregions))
  }, 10)

  useEffect(
    () => {
      // if there is no window, we cannot render this component
      if (!hasWindow) {
        return null
      }

      const { bounds, maxBounds, minZoom, maxZoom } = config
      const { center, zoom } = getCenterAndZoom(mapNode.current, bounds, 0)

      // Token must be set before constructing map
      mapboxgl.accessToken = mapboxToken

      const map = new mapboxgl.Map({
        container: mapNode.current,
        style: 'mapbox://styles/mapbox/light-v9',
        center,
        zoom,
        minZoom,
        maxZoom,
        maxBounds,
      })
      mapRef.current = map
      window.map = map // for easier debugging and querying via console

      if (!isMobile) {
        map.addControl(new mapboxgl.NavigationControl(), 'top-right')
      }

      map.on('load', () => {
        // due to styling components loading at different types, the containing
        // nodes don't always have height set; force larger view
        if (isLocalDev) {
          map.resize()
        }

        // add sources
        Object.entries(sources).forEach(([id, source]) => {
          map.addSource(id, source)
        })

        // add DeckGL pixel layer
        // by default, renders the blueprint
        const deckGLOverlay = new MapboxOverlay({
          interleaved: true,

          layers: [
            new StackedPNGTileLayer({
              id: 'pixelLayers',
              beforeId: beforeLayer,
              refinementStrategy: 'no-overlap',
              layers: pixelLayers,
              extent: bounds,
              maxRequests: 20, // because these are on HTTP/2, we can fetch many at once
              opacity: 0.7,
              filters: null,
              visible: false,
              renderLayer,
            }),
          ],
        })

        map.addControl(deckGLOverlay)

        map.once('idle', () => {
          // update state once to trigger other components to update with map object
          setIsLoaded(() => true)
        })

        // add normal mapbox layers// add layers
        layers.forEach((layer) => {
          map.addLayer(layer, beforeLayer)
        })

        // if map is initialized in pixel or filter mode
        if (mapMode === 'pixel' || mapMode === 'filter') {
          map.setLayoutProperty('unit-fill', 'visibility', 'none')
          map.setLayoutProperty('unit-outline', 'visibility', 'none')
          map.setLayoutProperty('blueprint', 'visibility', 'none')

          setPixelLayerProps(map, {
            visible: true,
            filters: null,
            data: { visible: true },
          })

          map.setLayoutProperty('ownership', 'visibility', 'visible')
          map.setLayoutProperty('subregions', 'visibility', 'visible')

          map.once('idle', getPixelData)
        }

        // enable event listener for renderer
        if (mapMode === 'pixel') {
          map.getLayer('pixelLayers').implementation.deck.setProps({
            onAfterRender: deckGLHandler.handler,
          })
        }

        setCurrentZoom(map.getZoom())

        map.on('move', () => {
          if (mapModeRef.current === 'pixel') {
            getPixelData()
          }
        })

        map.on('moveend', () => {
          mapIsDrawingRef.current = true
          if (mapModeRef.current === 'filter') {
            updateVisibleSubregions()
          }
          updateMapIsDrawing()
        })

        map.on('zoomend', () => {
          if (mapModeRef.current === 'pixel') {
            getPixelData()
          } else if (mapModeRef.current === 'filter') {
            updateVisibleSubregions()
          }
          setCurrentZoom(map.getZoom())
        })
      })

      map.on('idle', () => {
        mapIsDrawingRef.current = false
        setMapIsDrawing(false)
      })

      map.on('click', ({ lngLat: point }) => {
        if (mapModeRef.current === 'pixel') {
          return
        }

        const features = map.queryRenderedFeatures(map.project(point), {
          layers: ['unit-fill'],
        })

        if (!(features && features.length > 0)) {
          setMapData(null)
          if (isMobile) {
            map.resize()
          }
          return
        }

        const { properties } = features[0]

        // highlight selected
        map.setFilter('unit-outline-highlight', ['==', 'id', properties.id])

        setMapData(
          unpackFeatureData(
            properties,
            ecosystemInfo,
            indicatorInfo,
            subregionIndex
          )
        )
        if (isMobile) {
          map.resize()
        }
      })

      // Highlight units on mouseover
      map.on('mousemove', 'unit-fill', ({ features }) => {
        if (!map.isStyleLoaded()) {
          return
        }

        map.getCanvas().style.cursor = 'pointer'

        if (!(features && features.length > 0)) {
          return
        }

        const { id } = features[0]

        const { current: prevId } = highlightIDRef
        if (prevId !== null && prevId !== id) {
          map.setFeatureState(
            { source: 'mapUnits', sourceLayer: 'units', id: prevId },
            { highlight: false }
          )
        }
        map.setFeatureState(
          { source: 'mapUnits', sourceLayer: 'units', id },
          { highlight: true }
        )
        highlightIDRef.current = id
      })

      // Unhighlight all hover features on mouseout
      map.on('mouseout', () => {
        if (!map.isStyleLoaded()) {
          return
        }

        const { current: prevId } = highlightIDRef
        if (prevId !== null) {
          map.setFeatureState(
            { source: 'mapUnits', sourceLayer: 'units', id: prevId },
            { highlight: false }
          )
        }
      })

      // when this component is destroyed, remove the map
      return () => {
        map.remove()
      }
    },
    // intentionally omitting getPixelData
    /* eslint-disable-next-line react-hooks/exhaustive-deps */
    [isMobile, setMapData]
  )

  // handler for changed mapMode
  useEffect(
    () => {
      mapModeRef.current = mapMode

      if (!isLoaded) return
      const { current: map } = mapRef

      // use a callback to actually update the layers, since may style may still
      // be loading
      const updateVisibleLayers = () => {
        mapIsDrawingRef.current = true
        updateMapIsDrawing()

        const isVisible = isRenderLayerVisibleRef.current
        const pixelLayer = map.getLayer('pixelLayers').implementation

        // toggle layer visibility
        if (mapMode === 'unit') {
          map.setLayoutProperty('unit-fill', 'visibility', 'visible')
          map.setLayoutProperty('unit-outline', 'visibility', 'visible')
          map.setLayoutProperty(
            'blueprint',
            'visibility',
            isVisible ? 'visible' : 'none'
          )
          map.setLayoutProperty('ownership', 'visibility', 'none')
          map.setLayoutProperty('subregions', 'visibility', 'none')

          // disable pixel layer event listener
          pixelLayer.deck.setProps({
            onAfterRender: () => {}, // no-op
          })
          setPixelLayerProps(map, {
            visible: false,
            filters: null, // reset filters (also reset in parent state)
            data: { visible: false },
          })
        } else {
          const activeFilters = filtersRef.current
          if (mapMode === 'pixel') {
            // enable pixel layer event listener
            pixelLayer.deck.setProps({
              onAfterRender: deckGLHandler.handler,
            })

            // immediately try to retrieve pixel data if in pixel mode
            if (map.getZoom() >= minPixelLayerZoom) {
              map.once('idle', getPixelData)
            }
          } else {
            // disable pixel layer event listener
            pixelLayer.deck.setProps({
              onAfterRender: () => {}, // no-op
            })
          }

          map.setLayoutProperty('unit-fill', 'visibility', 'none')
          map.setLayoutProperty('unit-outline', 'visibility', 'none')
          map.setLayoutProperty('blueprint', 'visibility', 'none')

          // reset selected outline
          map.setFilter('unit-outline-highlight', ['==', 'id', Infinity])

          map.setLayoutProperty('ownership', 'visibility', 'visible')
          map.setLayoutProperty('subregions', 'visibility', 'visible')
          setPixelLayerProps(map, {
            visible: true,
            filters: activeFilters,
            // have to use opacity to hide so that pixel mode still works when hidden
            opacity: isVisible ? 0.7 : 0,
            // TODO: do we still need data prop?  E.g., when toggling to visible to force tiles to load
            // data prop is used to force deeper reloading of tiles
            data: { visible: true },
          })

          if (mapMode === 'filter') {
            map.once('idle', updateVisibleSubregions)
          }
        }
      }

      if (!map.isStyleLoaded()) {
        map.once('idle', updateVisibleLayers)

        // stop any transitions underway
        map.stop()

        return
      }
      // stop any transitions underway
      map.stop()

      updateVisibleLayers()
    },

    // intentionally omitting getPixelData; it is static
    /* eslint-disable-next-line react-hooks/exhaustive-deps */
    [isLoaded, mapMode]
  )

  // handler for changed mapData
  useIsEqualEffect(() => {
    if (!isLoaded) return
    const { current: map } = mapRef

    // sometimes map is not fully loaded on hot reload
    if (!map.loaded() || mapModeRef.current === 'pixel') return

    if (mapData === null) {
      map.setFilter('unit-outline-highlight', ['==', 'id', Infinity])
    }
  }, [mapData, isLoaded])

  // handler to update rendered layer
  useIsEqualEffect(() => {
    if (!isLoaded) return
    const { current: map } = mapRef

    setPixelLayerProps(map, { renderLayer })
  }, [renderLayer])

  // handler to update filters
  useIsEqualEffect(() => {
    if (!isLoaded) return
    const { current: map } = mapRef

    const activeFilters = Object.entries(filters)
      /* eslint-disable-next-line no-unused-vars */
      .filter(([_, { enabled }]) => enabled)
      .reduce(
        (prev, [id, { activeValues }]) =>
          Object.assign(prev, { [id]: activeValues }),
        {}
      )

    filtersRef.current = activeFilters

    setPixelLayerProps(map, { filters: activeFilters })
  }, [filters])

  // handler for setting location
  useIsEqualEffect(() => {
    if (!isLoaded) return

    if (location !== null) {
      const { current: map } = mapRef
      const { latitude, longitude } = location
      map.jumpTo({ center: [longitude, latitude], zoom: 12 })

      if (locationMarkerRef.current === null) {
        locationMarkerRef.current = new mapboxgl.Marker()
          .setLngLat([longitude, latitude])
          .addTo(map)
      } else {
        locationMarkerRef.current.setLngLat([longitude, latitude])
      }
    } else if (locationMarkerRef.current !== null) {
      locationMarkerRef.current.remove()
      locationMarkerRef.current = null
    }
  }, [location, isLoaded])

  const handleToggleRenderLayerVisible = useCallback(() => {
    const { current: map } = mapRef
    if (!map) return

    setisRenderLayerVisible((prevVisible) => {
      const newIsVisible = !prevVisible
      isRenderLayerVisibleRef.current = newIsVisible
      if (mapModeRef.current === 'unit') {
        map.setLayoutProperty(
          'blueprint',
          'visibility',
          newIsVisible ? 'visible' : 'none'
        )
      } else {
        // have to toggle opacity not visibility so that pixel-level identify
        // still works
        setPixelLayerProps(map, { opacity: newIsVisible ? 0.7 : 0 })
      }
      return newIsVisible
    })
  }, [])

  const handleBasemapChange = useCallback(
    (styleID) => {
      const { current: map } = mapRef

      if (!isLoaded) {
        return
      }

      const updateStyle = () => {
        const {
          style: {
            _layers: {
              pixelLayers: { implementation: pixelLayer },
            },
          },
        } = map

        map.setStyle(`mapbox://styles/mapbox/${styleID}`)

        map.once('style.load', () => {
          const {
            sources: styleSources,
            layers: styleLayers,
            metadata: { 'mapbox:origin': curStyleId },
          } = map.getStyle()
          const layerIndex = indexBy(styleLayers, 'id')

          if (curStyleId === 'satellite-streets-v11') {
            // make satellite a bit more washed out
            map.setPaintProperty('background', 'background-color', '#FFF')
            map.setPaintProperty('satellite', 'raster-opacity', 0.75)
          }

          // add sources back
          Object.entries(sources).forEach(([id, source]) => {
            // make sure we're not trying to reload the same style, which already has these
            if (!styleSources[id]) {
              map.addSource(id, source)
            }
          })

          // add regular layers and reapply filters / visibility
          layers.forEach((l) => {
            // make sure we're not trying to reload the same layers
            if (layerIndex[l.id]) {
              return
            }

            const layer = { ...l }

            if (mapMode !== 'unit') {
              if (
                l.id === 'blueprint' ||
                l.id === 'unit-fill' ||
                l.id === 'unit-outline'
              ) {
                layer.layout = {
                  visibility: 'none',
                }
              }
              if (l.id === 'ownership' || l.id === 'subregions') {
                layer.layout = {
                  visibility: 'visible',
                }
              }
            } else {
              if (l.id === 'blueprint' && !isRenderLayerVisibleRef.current) {
                layer.layout = {
                  visibility: 'none',
                }
              }
              if (l.id === 'unit-outline-highlight' && mapData !== null) {
                // re-highlight selected layer
                layer.filter = ['==', 'id', mapData.id]
              }
            }

            map.addLayer(layer, beforeLayer)
          })

          map.addLayer(pixelLayer, beforeLayer)
        })
      }

      // wait for previous to finish loading, if necessary
      if (map.isStyleLoaded()) {
        updateStyle()
      } else {
        map.once('idle', updateStyle)
      }
    },
    [isLoaded, mapData, mapMode]
  )

  let belowMinZoom = false
  if (mapMode === 'pixel') {
    belowMinZoom = currentZoom < minPixelLayerZoom
  } else if (mapMode === 'unit') {
    belowMinZoom = currentZoom < minSummaryZoom
  }

  return (
    <Box
      sx={{
        width: '100%',
        height: '100%',
        flex: '1 1 auto',
        position: 'relative',
        ...mapWidgetCSS,
      }}
    >
      <Box
        ref={mapNode}
        sx={{
          width: '100%',
          height: '100%',
          '& canvas': {
            borderLeftColor: 'grey.3',
            borderLeftWidth: ['0px', '2px'],
            borderLeftStyle: 'solid',
            '&:focus-visible': {
              borderLeftColor: 'blue !important',
            },
          },
        }}
      />

      {mapIsDrawing ? (
        <Flex
          sx={{
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            bg: 'rgba(255, 255, 255, .5)',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <Spinner duration={750} />
        </Flex>
      ) : null}

      {mapMode === 'pixel' && currentZoom >= minPixelLayerZoom ? (
        <Box
          sx={{
            position: 'absolute',
            zIndex: 0,
            left: '50%',
            top: '50%',
            ml: '-1rem',
            mt: '-1rem',
            pointerEvents: 'none',
          }}
        >
          <img
            src={CrosshairsIcon}
            style={{
              position: 'absolute',
              zIndex: 2,
              left: 0,
              top: 0,
              bottom: 0,
              right: 0,
              width: '32px',
              height: '32px',
            }}
            alt="Crosshairs icon"
          />
        </Box>
      ) : null}

      {/* Only show widgets after loading to prevent map from getting out of sync */}
      {isLoaded ? (
        <>
          {!isMobile ? (
            <>
              <Legend
                title={renderLayer.label}
                subtitle={renderLayer.valueLabel}
                categories={renderLayer.categories}
                isVisible={isRenderLayerVisible}
                onToggleVisibility={handleToggleRenderLayerVisible}
              />
              {mapMode !== 'unit' && !hidePixelLayerToggle ? (
                <LayerToggle />
              ) : null}

              <FindLocation />
            </>
          ) : null}

          <MapModeToggle
            map={mapRef.current}
            isMobile={isMobile}
            belowMinZoom={belowMinZoom}
          />

          <StyleToggle
            isMobile={isMobile}
            onStyleChange={handleBasemapChange}
          />
        </>
      ) : null}
    </Box>
  )
}

// prevent rerender on props change
export default memo(Map, () => true)
