// ui/src/lib/components/tabs/moreinfo/WildfireRisk.svelte
<script lang="ts">
	import CheckIcon from '~icons/fa-solid/check'
	import { PercentBarChart } from '$lib/components/chart'
	import { wildfireRisk as categories } from '$lib/config/constants'
	import { cn } from '$lib/utils'

	const { type, wildfireRisk, subregions } = $props()

	const bars = $derived(
		categories.map((category) => ({
			...category,
			percent: wildfireRisk ? wildfireRisk[category.value] || 0 : 0
		}))
	)
</script>

<div class="not-first:mt-8 not-first:border-t not-first:border-t-grey-2 not-first:pt-8">
	<h3 class="text-2xl">Wildfire Likelihood</h3>

	{#if type === 'pixel'}
		{#if wildfireRisk === null}
			<div class="text-grey-8">
				Wildfire likelihood data is not currently available for this area.
			</div>
		{:else}
			<div class="text-grey-8">Annual burn probability:</div>

			<div class="ml-2 mt-2">
				{#each categories as { value, label }}
					<div
						class="flex items-baseline justify-between pl-2 border-b border-b-grey-2 pb-1 not-first:mt-1 gap-4"
					>
						<div
							class={cn('flex-auto text-grey-8', {
								'text-foreground font-bold': value === wildfireRisk
							})}
						>
							{label}
						</div>
						<CheckIcon
							class={cn('size-4 flex-none invisible', { visible: value === wildfireRisk })}
						/>
					</div>
				{/each}
			</div>
		{/if}
	{/if}

	{#if type !== 'pixel'}
		{#if (subregions && subregions.has('Caribbean')) || wildfireRisk === null}
			<div class="text-grey-8">
				Wildfire likelihood data is not currently available for this area.
			</div>
		{/if}

		<div class="text-grey-8 leading-tight">
			Area in each wildfire probability category within this subwatershed:
		</div>
		<div class="mt-4">
			{#each bars as bar}
				<PercentBarChart {...bar} class="mt-2 mb-4" />
			{/each}
		</div>
	{/if}

	<!-- don't show data info in Caribbean -->
	{#if !(subregions && subregions.has('Caribbean'))}
		<div class="mt-8 text-grey-8 leading-tight">
			Wildfire likelihood data derived from the{' '}
			<a href="https://wildfirerisk.org/" target="_blank"> Wildfire Risk to Communities </a>{' '}
			project by the USDA Forest Service.
		</div>
	{/if}
</div>

// ui/src/content/MoreInfoTab/WildfireRisk.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Flex, Text } from 'theme-ui'
import { Check } from '@emotion-icons/fa-solid'

import { wildfireRisk as wildfireRiskCategories } from 'config'
import { OutboundLink } from 'components/link'
import { PercentBarChart } from 'components/chart'

const DataSource = () => (
  <Text sx={{ mt: '2rem', color: 'grey.8', fontSize: 1 }}>
    Wildfire likelihood data derived from the{' '}
    <OutboundLink to="https://wildfirerisk.org/">
      Wildfire Risk to Communities
    </OutboundLink>{' '}
    project by the USDA Forest Service.
  </Text>
)

const WildfireRisk = ({ type, wildfireRisk, subregions }) => {
  const bars = wildfireRiskCategories.map((category) => ({
    ...category,
    percent: wildfireRisk ? wildfireRisk[category.value] || 0 : 0,
    color: 'grey.9',
  }))

  if (type === 'pixel') {
    if (wildfireRisk === null) {
      return (
        <Box>
          <Text sx={{ color: 'grey.8' }}>
            Wildfire likelihood data is not currently available for this area.
          </Text>
        </Box>
      )
    }

    // show wildfire risk classes with checkmarks
    return (
      <Box>
        <Flex sx={{ justifyContent: 'space-between' }}>
          <Text sx={{ color: 'grey.8' }}>Annual burn probability:</Text>
        </Flex>
        <Box sx={{ ml: '0.5rem', mt: '0.5rem' }}>
          {wildfireRiskCategories.map(({ value, label }) => (
            <Flex
              key={value}
              sx={{
                alignItems: 'baseline',
                justifyContent: 'space-between',
                pl: '0.5rem',
                borderBottom: '1px solid',
                borderBottomColor: 'grey.2',
                pb: '0.25rem',
                '&:not(:first-of-type)': {
                  mt: '0.25rem',
                },
              }}
            >
              <Text
                sx={{
                  flex: '1 1 auto',
                  color: value === wildfireRisk ? 'text' : 'grey.8',
                  fontWeight: value === wildfireRisk ? 'bold' : 'normal',
                }}
              >
                {label}
              </Text>
              {value === wildfireRisk ? (
                <Box sx={{ flex: '0 0 auto' }}>
                  <Check size="1em" />
                </Box>
              ) : null}
            </Flex>
          ))}
        </Box>
        <DataSource />
      </Box>
    )
  }

  if ((subregions && subregions.has('Caribbean')) || wildfireRisk === null) {
    return (
      <Box>
        <Text sx={{ color: 'grey.8' }}>
          Wildfire likelihood data is not currently available for this area.
        </Text>
      </Box>
    )
  }

  return (
    <>
      <Text sx={{ color: 'grey.8' }}>
        Area in each wildfire probability category within this subwatershed:
      </Text>
      {bars.map((bar) => (
        <PercentBarChart
          key={bar.value}
          {...bar}
          sx={{ mt: '0.5rem', mb: '1rem' }}
        />
      ))}
      <DataSource />
    </>
  )
}

WildfireRisk.propTypes = {
  type: PropTypes.string.isRequired,
  wildfireRisk: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.number),
    PropTypes.number,
  ]),
  subregions: PropTypes.object,
}

WildfireRisk.defaultProps = {
  wildfireRisk: null,
  subregions: null,
}

export default WildfireRisk
