// ui/src/lib/components/tabs/moreinfo/SLR.svelte
<script lang="ts">
	import { slrNodata } from '$lib/config/constants'
	import { formatPercent } from '$lib/util/format'
	import SLRChart from './SLRChart.svelte'

	const { type, depth, nodata } = $props()

	const { nodataValue, nodataItems } = $derived.by(() => {
		let value = null
		const items = []

		if (type !== 'pixel') {
			for (let i = 0; i < 3; i += 1) {
				// if mostly a single type of nodata, just return that
				if (nodata[i] >= 99) {
					value = i
				}
				if (nodata[i] > 1) {
					items.push(
						`${slrNodata[i].label
							.toLowerCase()
							.replace(/this area is/g, '')
							.replace(/for this area/g, '')
							.trim()} (${formatPercent(nodata[i])}% of area)`
					)
				}
			}
		}

		return { nodataValue: value, nodataItems: items }
	})
</script>

<div class="not-first:mt-8 not-first:border-t not-first:border-t-grey-2 not-first:pt-8">
	<h3 class="text-2xl">Sea Level Rise</h3>

	{#if type === 'pixel'}
		{#if nodata !== null}
			<div>{slrNodata[nodata].label}.</div>
		{:else if depth === null}
			<div>{slrNodata[2].label}.</div>
		{:else if depth === 0}
			<div>This area is already inundated.</div>
		{:else}
			<div>
				This area is projected to be inundated at{' '}
				<b>
					{depth}
					{depth === 1 ? 'foot' : 'feet'}
				</b>{' '}
				of sea-level rise.
			</div>
		{/if}
	{/if}

	<!-- split at top-level into 2 conditional trees for cleaner logic -->
	{#if type !== 'pixel'}
		{#if nodataValue !== null}
			<div>{slrNodata[nodataValue].label}.</div>
		{:else if !(depth && depth.length > 0)}
			<div>{slrNodata[2].label}.</div>
		{:else}
			<div class="text-grey-8 leading-tight">
				Extent of flooding by projected sea level rise within this subwatershed:
			</div>
			<SLRChart data={depth.map((y: number, i: number) => ({ x: i, y }))} />

			{#if nodataItems.length > 0}
				<div class="mt-8 text-grey-8 leading-tight">
					This subwatershed has additional areas not included in the chart above: {nodataItems.join(
						', '
					)}.
				</div>
			{/if}
		{/if}
	{/if}

	<div class="mt-8 text-grey-8 leading-tight">
		Sea level rise estimates derived from the
		<a href="https://coast.noaa.gov/digitalcoast/data/slr.html" target="_blank">
			NOAA sea-level rise inundation data
		</a>. To explore additional SLR information, please see NOAA&apos;s
		<a href="https://coast.noaa.gov/slr/" target="_blank"> Sea Level Rise Viewer </a>.
	</div>
</div>

// ui/src/content/ThreatsTab/SLR.jsx
import React from 'react'
import PropTypes from 'prop-types'

import { Box, Text } from 'theme-ui'

import { useSLR } from 'components/data'
import { OutboundLink } from 'components/link'
import { LineChart } from 'components/chart'
import { formatPercent } from 'util/format'

const DataSource = () => (
  <Text sx={{ mt: '2rem', color: 'grey.7', fontSize: 1 }}>
    Sea level rise estimates derived from the{' '}
    <OutboundLink to="https://coast.noaa.gov/digitalcoast/data/slr.html">
      NOAA sea-level rise inundation data
    </OutboundLink>
    . To explore additional SLR information, please see NOAA&apos;s{' '}
    <OutboundLink to="https://coast.noaa.gov/slr/">
      Sea Level Rise Viewer
    </OutboundLink>
    .
  </Text>
)

// SLR depth levels are in feet above current mean sea level: 0...10
const SLR = ({ type, depth, nodata }) => {
  const { nodata: nodataCategories } = useSLR()

  if (type === 'pixel') {
    if (nodata !== null) {
      return (
        <Box>
          <Text>{nodataCategories[nodata].label}.</Text>
          <DataSource />
        </Box>
      )
    }
    if (depth === null) {
      return (
        <Box>
          <Text sx={{ color: 'grey.7' }}>{nodataCategories[2].label}.</Text>
          <DataSource />
        </Box>
      )
    }

    if (depth === 0) {
      return (
        <Box>
          <Text>This area is already inundated.</Text>
          <DataSource />
        </Box>
      )
    }

    return (
      <Box>
        <Text>
          This area is projected to be inundated at{' '}
          <b>
            {depth} {depth === 1 ? 'foot' : 'feet'}
          </b>{' '}
          of sea-level rise.
        </Text>
        <DataSource />
      </Box>
    )
  }

  const nodataItems = []
  if (nodata && nodata.length > 0) {
    for (let i = 0; i < 3; i += 1) {
      // if pixel mode or mostly a single type of nodata, return just that
      if ((type === 'pixel' && nodata === i) || nodata[i] >= 99) {
        return (
          <Box>
            <Text sx={{ color: 'grey.7' }}>{nodataCategories[i].label}.</Text>
            <DataSource />
          </Box>
        )
      }
      if (nodata[i] > 1) {
        nodataItems.push(
          `${nodataCategories[i].label
            .toLowerCase()
            .replace(/this area is/g, '')
            .replace(/for this area/g, '')
            .trim()} (${formatPercent(nodata[i])}% of area)`
        )
      }
    }
  }

  if (!(depth && depth.length > 0)) {
    return (
      <Box>
        <Text sx={{ color: 'grey.7' }}>{nodataCategories[2].label}.</Text>
        <DataSource />
      </Box>
    )
  }

  return (
    <>
      <Text sx={{ color: 'grey.7' }}>
        Extent of flooding by projected sea level rise within this subwatershed:
      </Text>

      <Box
        sx={{
          height: '200px',
          '& text': {
            fontSize: 1,
            fill: 'grey.7',
          },
        }}
      >
        <LineChart
          data={depth.map((y, i) => ({ x: i, y }))}
          fontSize={10}
          yTicks={5}
          xTicks={depth.length}
          yLabel="Percent of area"
          yLabelOffset={48}
          xLabel="Amount of sea level rise (feet)"
          xLabelOffset={40}
          areaColor="#004da8"
          areaOpacity={0.6}
          pointColor="#004da8"
          lineColor="#004da8"
          lineWidth={2}
          margin={{ left: 60, right: 10, top: 10, bottom: 50 }}
        />
      </Box>
      {nodataItems.length > 0 ? (
        <Text sx={{ mt: '2rem', color: 'grey.7', fontSize: 1 }}>
          This subwatershed has additional areas not included in the chart
          above: {nodataItems.join(', ')}.
        </Text>
      ) : null}
      <DataSource />
    </>
  )
}

SLR.propTypes = {
  type: PropTypes.string.isRequired,
  depth: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.number),
    PropTypes.number,
  ]),
  nodata: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.number),
    PropTypes.number,
  ]),
}

SLR.defaultProps = {
  depth: null,
  nodata: null,
}

export default SLR
