// ui/src/content/IndicatorsTab/IndicatorPercentChart.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Flex, Box, Text, Progress } from 'theme-ui'

import { formatPercent } from 'util/format'

const IndicatorPercentChart = ({ label, percent, percentSuffix, color }) => (
  <Box sx={{ flex: '1 1 auto' }}>
    <Flex
      sx={{
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        fontSize: 0,
      }}
    >
      <Text sx={{ flex: '1 1 auto' }}>{label}</Text>
      <Text sx={{ color: 'grey.8', flex: '0 0 auto', ml: '1em' }}>
        {formatPercent(percent)}% {percentSuffix}
      </Text>
    </Flex>
    <Progress value={percent} max={100} color={color} />
  </Box>
)

IndicatorPercentChart.propTypes = {
  label: PropTypes.string.isRequired,
  percent: PropTypes.number.isRequired,
  percentSuffix: PropTypes.string,
  color: PropTypes.string,
}

IndicatorPercentChart.defaultProps = {
  percentSuffix: '',
  color: 'grey.8',
}

export default IndicatorPercentChart

// ui/src/lib/components/tabs/indicators/IndicatorPercentChart.svelte
<script lang="ts">
	import { Progress } from '$lib/components/ui/progress'
	import { formatPercent } from '$lib/util/format'

	const { label, percent, percentSuffix = '' } = $props()
</script>

<div class="flex-auto">
	<div class="flex justify-between items-end text-sm">
		<div class="flex-auto">{label}</div>
		<div class="text-grey-8 ml-4 text-right grow-0 shrink-0 basis-10">
			{formatPercent(percent)}% {percentSuffix}
		</div>
	</div>
	<Progress value={percent} max={100} class="h-4 bg-grey-1 [&>div]:bg-grey-8" />
</div>
