// ui/src/content/IndicatorsTab/IndicatorDetails.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Flex, Text, Heading, Image } from 'theme-ui'
import { Reply } from '@emotion-icons/fa-solid'

import { OutboundLink } from 'components/link'
import { formatPercent } from 'util/format'
import NeedHelp from 'content/NeedHelp'
import { sum } from 'util/data'
import theme from 'theme'

import IndicatorPercentTable from './IndicatorPercentTable'
import { IndicatorPropType } from './proptypes'

const IndicatorDetails = ({
  type,
  label,
  ecosystem: { id: ecosystemId, label: ecosystemLabel, color, borderColor },
  description,
  url,
  goodThreshold,
  values,
  valueLabel,
  outsideSEPercent,
  onClose,
}) => {
  // eslint-disable-next-line global-require,import/no-dynamic-require
  const icon = require(`images/${ecosystemId}.svg`).default

  const totalIndicatorPercent = sum(values.map(({ percent }) => percent))

  const percentTableValues = values
    .map((value, i) => ({
      ...value,
      isHighValue: i === values.length - 1,
      isLowValue: i === 0,
    }))
    .reverse()

  const notEvaluatedPercent = 100 - outsideSEPercent - totalIndicatorPercent
  if (notEvaluatedPercent >= 1) {
    percentTableValues.push({
      value: -1,
      label: 'Not evaluated for this indicator',
      percent: notEvaluatedPercent,
    })
  }

  if (outsideSEPercent >= 1) {
    percentTableValues.push({
      value: -3,
      label: 'Outside Southeast Blueprint',
      percent: outsideSEPercent,
    })
  }

  return (
    <Flex
      sx={{
        flexDirection: 'column',
        height: '100%',
        overflowY: 'hidden',
      }}
    >
      <Box
        sx={{
          cursor: 'pointer',
          bg: color,
          py: ['1rem', '0.5rem'],
          pl: '0.25rem',
          pr: '1rem',
          borderBottom: '1px solid',
          borderBottomColor: borderColor,
        }}
      >
        <Flex
          onClick={onClose}
          sx={{
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <Flex>
            <Text sx={{ color: theme.colors.grey[7], flex: '0 0 auto' }}>
              <Reply
                size="0.75em"
                style={{
                  display: 'block',
                  margin: 0,
                }}
              />
            </Text>

            <Flex sx={{ flex: '1 1 auto', alignItems: 'center' }}>
              <Image
                src={icon}
                sx={{
                  flex: '0 0 auto',
                  width: '2.5em',
                  height: '2.5em',
                  mr: '0.5em',
                  bg: '#FFF',
                  borderRadius: '2.5em',
                }}
              />
              <Box sx={{ pr: '0.25rem' }}>
                <Text sx={{ fontSize: 0, color: 'grey.8' }}>
                  {ecosystemLabel}
                </Text>
                <Heading as="h4">{label}</Heading>
              </Box>
            </Flex>
          </Flex>

          {type !== 'pixel' ? (
            <Box
              sx={{
                flex: '0 0 auto',
                color: 'grey.8',
                fontSize: 0,
                textAlign: 'right',
              }}
            >
              <b>{formatPercent(totalIndicatorPercent)}%</b>
              <br />
              of area
            </Box>
          ) : null}
        </Flex>
      </Box>

      <Box
        sx={{
          px: '1rem',
          pb: '1rem',
          height: '100%',
          flex: '1 1 auto',
          overflowY: 'auto',
        }}
      >
        {valueLabel ? (
          <Text sx={{ mt: '1rem', mb: '-1.5rem', fontWeight: 'bold' }}>
            {valueLabel}:
          </Text>
        ) : null}

        <IndicatorPercentTable
          type={type}
          values={percentTableValues}
          goodThreshold={goodThreshold}
        />

        <Box
          sx={{
            mt: type === 'pixel' ? '0.25rem' : '0.5rem',
            fontSize: 1,
            lineHeight: 1.3,
          }}
        >
          {/* handle links */}
          {description.search(/<a/g) !== -1 ? (
            <div dangerouslySetInnerHTML={{ __html: description }} />
          ) : (
            description
          )}
        </Box>

        <Box sx={{ mt: '2rem' }}>
          To learn more and explore the GIS data,{' '}
          <OutboundLink to={url}>
            view this indicator in the SECAS Atlas
          </OutboundLink>
          .
        </Box>
        <NeedHelp />
      </Box>
    </Flex>
  )
}

IndicatorDetails.propTypes = {
  type: PropTypes.string.isRequired,
  ...IndicatorPropType,
  outsideSEPercent: PropTypes.number,
  onClose: PropTypes.func.isRequired,
}

IndicatorDetails.defaultProps = {
  outsideSEPercent: 0,
}

export default IndicatorDetails

// ui/src/lib/components/tabs/indicators/IndicatorDetails.svelte
<script lang="ts">
	import { getContext } from 'svelte'

	import ReplyIcon from '~icons/fa-solid/reply'
	import { Button } from '$lib/components/ui/button'
	import type { MapData } from '$lib/components/map'
	import { formatPercent } from '$lib/util/format'
	import { sum } from '$lib/util/data'
	import { cn } from '$lib/utils'

	import { NeedHelp } from '../general'
	import IndicatorPercentTable from './IndicatorPercentTable.svelte'

	const {
		type,
		label,
		ecosystem,
		description,
		url,
		goodThreshold,
		values,
		valueLabel,
		outsideSEPercent,
		icon,
		class: className = ''
	} = $props()

	const mapData: MapData = getContext('map-data')

	const { totalIndicatorPercent, percentTableValues } = $derived.by(() => {
		const totalPercent = sum(values.map(({ percent }: { percent: number }) => percent))

		const tableValues = values
			.map((value: object, i: number) => ({
				...value,
				isHighValue: i === values.length - 1,
				isLowValue: i === 0
			}))
			.reverse()

		const notEvaluatedPercent = 100 - outsideSEPercent - totalPercent
		if (notEvaluatedPercent >= 1) {
			tableValues.push({
				value: -1,
				label: 'Not evaluated for this indicator',
				percent: notEvaluatedPercent
			})
		}

		if (outsideSEPercent >= 1) {
			tableValues.push({
				value: -3,
				label: 'Outside Southeast Blueprint',
				percent: outsideSEPercent
			})
		}

		return {
			percentTableValues: tableValues,
			totalIndicatorPercent: totalPercent
		}
	})
</script>

<div class="flex flex-col h-full overflow-hidden">
	<Button
		class="shadow-none rounded-none flex justify-between items-center py-4 md:py-2 pl-1 pr-4 border-b text-foreground text-wrap whitespace-break-spaces h-auto gap-4"
		style={`background-color:${ecosystem.color}; border-color:${ecosystem.borderColor};`}
		onclick={() => (mapData.selectedIndicator = null)}
	>
		<div class="flex items-start">
			<ReplyIcon class="size-3 flex-none text-grey-7" />
			<div class="flex gap-2 flex-auto items-center">
				<img
					src={icon}
					alt={`${ecosystem.label} icon`}
					class="flex-none size-10 bg-white rounded-full block"
				/>
				<div class="flex flex-col leading-tight items-start text-left">
					<div class="font-sm color-grey-8">
						{ecosystem.label}
					</div>
					<h4 class="text-xl leading-tight">
						{label}
					</h4>
				</div>
			</div>
		</div>
		{#if type !== 'pixel'}
			<div class="flex-none text-grey-8 text-sm text-right leading-tight">
				<b>{formatPercent(totalIndicatorPercent)}%</b>
				<br />
				of area
			</div>
		{/if}
	</Button>

	<div class="px-4 pb-4 h-full flex-auto overflow-y-auto">
		{#if valueLabel}
			<div class="mt-4 -mb-6 font-bold">{valueLabel}:</div>
		{/if}

		<IndicatorPercentTable values={percentTableValues} {goodThreshold} />

		<div
			class={cn('text-md leading-snug mt-2', {
				'mt-1': type === 'pixel'
			})}
		>
			{#if description.search(/<a/g) !== -1}
				TODO: dangerously set inner HTML
			{:else}
				{description}
			{/if}
		</div>

		<div class="mt-8">
			To learn more and explore the GIS data,{' '}
			<a href={url} target="_blank"> view this indicator in the SECAS Atlas </a>.
		</div>

		<NeedHelp />
	</div>
</div>
