// ui/src/content/IndicatorsTab/PixelIndicatorListItem.jsx
import React, { useCallback } from 'react'
import PropTypes from 'prop-types'
import { Box, Text } from 'theme-ui'
import { lighten } from '@theme-ui/color'

import { useBreakpoints } from 'components/layout'

import IndicatorPixelValueChart from './IndicatorPixelValueChart'
import { IndicatorPropType } from './proptypes'

const PixelIndicatorListItem = ({ indicator, onSelect }) => {
  const { label, values, valueLabel, goodThreshold } = indicator
  const present = indicator.total > 0
  const [currentValue] = values.filter(({ percent }) => percent === 100)
  const isZeroValue =
    !present || (currentValue.value === 0 && !currentValue.color)

  const breakpoint = useBreakpoints()
  const isMobile = breakpoint === 0

  const handleClick = useCallback(() => {
    onSelect(indicator)
  }, [indicator, onSelect])

  return (
    <Box
      onClick={present && !isZeroValue ? handleClick : undefined}
      sx={{
        cursor: present && !isZeroValue ? 'pointer' : 'unset',
        px: '1rem',
        pt: '1rem',
        pb: '1.5rem',
        position: 'relative',
        '&:not(:first-of-type)': {
          borderTop: '2px solid',
          borderTopColor: 'grey.1',
        },
        ...(present && !isZeroValue
          ? {
              '&:hover': {
                bg: lighten('grey.0', 0.01),
                '& label': {
                  display: 'block',
                },
              },
            }
          : {}),
      }}
    >
      <Text
        sx={{
          color: present && !isZeroValue ? 'primary' : 'grey.8',
          fontSize: 2,
          fontWeight: present && !isZeroValue ? 'bold' : 'unset',
        }}
      >
        {label}
      </Text>

      <Box>
        <IndicatorPixelValueChart
          present={present}
          values={values}
          currentValue={currentValue}
          isZeroValue={isZeroValue}
          valueLabel={valueLabel}
          goodThreshold={goodThreshold}
        />
      </Box>

      {present && !isZeroValue ? (
        <Text
          as="label"
          sx={{
            color: 'primary',
            fontSize: 'small',
            textAlign: 'center',
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            display: 'none',
          }}
        >
          {isMobile ? 'tap' : 'click'} for more details
        </Text>
      ) : null}
    </Box>
  )
}

PixelIndicatorListItem.propTypes = {
  indicator: PropTypes.shape(IndicatorPropType).isRequired,
  onSelect: PropTypes.func.isRequired,
}

export default PixelIndicatorListItem

// ui/src/lib/components/tabs/indicators/PixelIndicatorListItem.svelte
<script lang="ts">
	import { getContext } from 'svelte'

	import { cn } from '$lib/utils'
	import type { MapData } from '$lib/components/map'
	import { Button } from '$lib/components/ui/button'

	import IndicatorPixelValueChart from './IndicatorPixelValueChart.svelte'

	const { indicator, onSelect } = $props()

	const mapData: MapData = getContext('map-data')

	let { isPresent, isZeroValue, currentValue } = $derived.by(() => {
		const present = indicator.total > 0
		const [value] = indicator.values.filter(({ percent }: { percent: number }) => percent === 100)
		const zeroVaue: boolean = !present || (value.value === 0 && !value.color)

		return {
			isPresent: present,
			currentValue: value,
			isZeroValue: zeroVaue
		}
	})
</script>

<Button
	onclick={!isZeroValue
		? () => {
				mapData.selectedIndicator = indicator.id
			}
		: () => {}}
	class={cn(
		'cursor-default shadow-none px-4 pt-4 pb-6 relative not-first:border-t-2 border-t-grey-1 group',
		{
			'cursor-pointer hover:bg-grey-0': !isZeroValue
		}
	)}
>
	<div
		class={cn('text-lg text-grey-8', {
			'text-primary font-bold': !isZeroValue
		})}
	></div>

	<IndicatorPixelValueChart {...indicator} {isPresent} {currentValue} {isZeroValue} />

	{#if !isZeroValue}
		<div
			class="text-primary font-sm text-center absolute bottom-0 top-0 left-0 right-0 hidden group-hover:block"
		>
			<div class="md:hidden">tap</div>
			<div class="hidden md:block">click</div>
			for more details
		</div>
	{/if}
</Button>
