// ui/src/components/layout/Footer.jsx
import React from 'react'
import { Box, Flex, Text } from 'theme-ui'
import {
  ExternalLinkAlt,
  Envelope,
  ExclamationCircle,
  Comments,
} from '@emotion-icons/fa-solid'

import { OutboundLink } from 'components/link'
import {
  ContactModal,
  FeedbackModal,
  ReportProblemModal,
} from 'components/modal'
import { useBreakpoints } from './Breakpoints'

const modalLinkCSS = {
  cursor: 'pointer',
  '&:hover': {
    textDecoration: 'underline',
  },
}

const Footer = () => {
  const breakpoint = useBreakpoints()
  const isMobile = breakpoint === 0

  if (isMobile) return null

  return (
    <Flex
      sx={{
        alignItems: 'center',
        justifyContent: 'space-between',
        fontSize: [0, 0, 0, 1],
        lineHeight: 1,
        px: '0.5em',
        py: '0.25em',
        bg: 'blue.9',
        color: '#FFF',
        a: {
          color: '#FFF',
        },
      }}
    >
      <Flex
        sx={{
          alignItems: 'center',
          px: '0.5em',
          mr: '0.5rem',
        }}
      >
        Version: Southeast Blueprint 2022
      </Flex>

      <Box
        sx={{
          borderLeft: '1px solid #FFF',
          height: '1em',
        }}
      />

      <Box sx={{ mx: '0.5em', flex: '0 0 auto' }}>
        <OutboundLink to="http://secassoutheast.org/blueprint">
          <Flex sx={{ alignItems: 'center', px: '0.5em' }}>
            <ExternalLinkAlt size="1em" style={{ marginRight: '0.5em' }} />
            <Text>Blueprint webpage</Text>
          </Flex>
        </OutboundLink>
      </Box>

      <Box
        sx={{ flex: '0 0 auto', borderLeft: '1px solid #FFF', height: '1em' }}
      />

      <Box sx={{ mx: '0.5em', flex: '0 0 auto' }}>
        <ContactModal>
          <Flex sx={{ alignItems: 'center', px: '0.5em' }}>
            <Envelope size="1em" style={{ marginRight: '0.5em' }} />
            <Text sx={modalLinkCSS}>Contact Us</Text>
          </Flex>
        </ContactModal>
      </Box>

      <Box
        sx={{
          display: ['none', 'none', 'unset'],
          flex: '0 0 auto',
          borderLeft: '1px solid #FFF',
          height: '1em',
        }}
      />

      <Box
        sx={{
          mx: '0.5em',
          display: ['none', 'none', 'unset'],
          flex: '0 0 auto',
        }}
      >
        <ReportProblemModal>
          <Flex sx={{ alignItems: 'center', px: '0.5em' }}>
            <ExclamationCircle size="1em" style={{ marginRight: '0.5em' }} />
            <Text sx={modalLinkCSS}>Report a Problem</Text>
          </Flex>
        </ReportProblemModal>
      </Box>

      <Box
        sx={{
          display: ['none', 'none', 'none', 'unset'],
          flex: '0 0 auto',
          borderLeft: '1px solid #FFF',
          height: '1em',
        }}
      />

      <Box
        sx={{ display: ['none', 'none', 'none', 'unset'], flex: '0 0 auto' }}
      >
        <FeedbackModal>
          <Flex sx={{ alignItems: 'center', px: '0.5em' }}>
            <Comments size="1em" style={{ marginRight: '0.5em' }} />
            <Text sx={modalLinkCSS}>Provide Feedback</Text>
          </Flex>
        </FeedbackModal>
      </Box>

      <Box
        sx={{
          flex: '0 0 auto',
          borderLeft: '1px solid #FFF',
          height: '1em',
          display: ['none', 'none', 'block'],
        }}
      />

      <Text
        sx={{
          flex: '1 1 auto',
          fontSize: 0,
          textAlign: 'right',
          ml: '0.5em',
          display: ['none', 'none', 'block'],
        }}
      >
        Created by U.S. Fish and Wildlife Service and{' '}
        <OutboundLink to="https://astutespruce.com">Astute Spruce</OutboundLink>
      </Text>
    </Flex>
  )
}

export default Footer

// ui/src/lib/components/layout/Footer.svelte
<script>
	import Comments from '~icons/fa-solid/comments'
	import Envelope from '~icons/fa-solid/envelope'
	import ExclamationCircle from '~icons/fa-solid/ExclamationCircle'
	import ExternalLinkAlt from '~icons/fa-solid/external-link-alt'

	import { ContactDialog, ProvideFeedbackDialog, ReportProblemDialog } from '$lib/components/dialog'
</script>

<footer
	class="hidden md:flex flex-none gap-4 items-center justify-between py-1 px-2 leading-none text-sm"
>
	<div class="flex flex-none gap-3 items-center">
		<div>Version: Southeast Blueprint 2025</div>
		<div>|</div>
		<a href="http://secassoutheast.org/blueprint" target="_blank" class="flex gap-2 items-center">
			<ExternalLinkAlt width="1em" height="1em" />
			Blueprint webpage
		</a>
		<div>|</div>
		<div class="flex-none">
			<ContactDialog>
				<div class="flex items-center gap-2 cursor-pointer hover:underline">
					<Envelope width="1em" height="1em" />
					Contact us
				</div>
			</ContactDialog>
		</div>
		<div class="hidden lg:block">|</div>
		<div class="flex-none">
			<ReportProblemDialog>
				<div class="items-center gap-2 cursor-pointer hover:underline hidden lg:flex">
					<ExclamationCircle width="1em" height="1em" />
					Report a problem
				</div>
			</ReportProblemDialog>
		</div>
		<div class="hidden lg:block">|</div>
		<div class="flex-none">
			<ProvideFeedbackDialog>
				<div class="items-center gap-2 cursor-pointer hover:underline hidden lg:flex">
					<Comments width="1em" height="1em" />
					Provide feedback
				</div>
			</ProvideFeedbackDialog>
		</div>
		<div class="hidden lg:block">|</div>
	</div>

	<div class="text-right">
		Created by the
		<span class="hidden xl:inline-block">U.S. Fish and Wildlife Service</span>
		<span class="inline-block xl:hidden">USFWS</span>
		and <a href="https://astutespruce.com" target="_blank">Astute Spruce</a>
	</div>
</footer>

<style>
	footer {
		background-color: #1e435b;
		color: #fff;
		a {
			color: #fff;
		}
	}
</style>
