// ui/src/lib/components/tabs/indicators/IndicatorPercentTable.svelte
<script lang="ts">
	import ArrowUpIcon from '~icons/fa-solid/arrow-up'
	import ArrowDownIcon from '~icons/fa-solid/arrow-down'
	import { cn } from '#lib/utils.js'

	import IndicatorPercentChart from './IndicatorPercentChart.svelte'
	import { formatPercent } from '#lib/util/format.js'
	const { values, goodThreshold } = $props()
	// remainder values, like area outside SE, are assigned values < 0
	const remainders = $derived(values.filter(({ value }: { value: number }) => value < 0))

	type Value = {
		value: number
		label: string
		percent: number
	}

	const { goodPercents, totalGoodPercent, notGoodPercents, totalNotGoodPercent } = $derived.by(
		() => {
			if (goodThreshold === null) {
				return
			}

			const good: Value[] = []
			let goodPercent = 0
			const notGood: Value[] = []
			let notGoodPercent = 0
			values.forEach(({ value, percent, ...rest }: Value) => {
				if (value >= goodThreshold) {
					good.push({ value, percent, ...rest })
					goodPercent += percent
				} else if (value >= 0 && value < goodThreshold) {
					notGood.push({ value, percent, ...rest })
					notGoodPercent += percent
				}
			})

			return {
				goodPercents: good,
				totalGoodPercent: goodPercent,
				notGoodPercents: notGood,
				totalNotGoodPercent: notGoodPercent
			}
		}
	)
</script>

<div class="my-8">
	{#if goodThreshold === null}
		{#each values.filter(({ value }: { value: number }) => value >= 0) as { value, label, percent, isHighValue, isLowValue } (value)}
			<div class={cn('flex not-first:mt-4 items-start', { 'items-end': isLowValue })}>
				<div class="flex items-center gap-1 flex-none w-20 font-bold text-sm">
					{#if isHighValue}
						<ArrowUpIcon class="size-4" />
						High:
					{:else if isLowValue}
						<ArrowDownIcon class="size-4" />
						Low:
					{/if}
				</div>
				<IndicatorPercentChart {label} {percent} />
			</div>
		{/each}
	{:else}
		{#each goodPercents as { value, label, percent, isHighValue } (value)}
			<div class="flex not-first:mt-4">
				<div class="flex items-center gap-1 flex-none w-20 font-bold text-sm">
					{#if isHighValue}
						<ArrowUpIcon class="size-4" />
						High:
					{/if}
				</div>
				<IndicatorPercentChart {label} {percent} />
			</div>
		{/each}

		<div class="mt-6 text-grey-8 text-sm">
			<div class="flex justify-center items-center gap-1">
				<ArrowUpIcon class="size-4" />
				<div class="w-[14em]">
					{formatPercent(totalGoodPercent)}% in good condition
				</div>
			</div>
			<div class="border-b border-dashed border-b-grey-8/60 h-[1px] my-2"></div>
			<div class="flex justify-center items-center gap-1">
				<ArrowDownIcon class="size-4" />
				<div class="w-[14em]">
					{formatPercent(totalNotGoodPercent)}% not in good condition
				</div>
			</div>
		</div>

		{#each notGoodPercents as { value, label, percent, isLowValue } (value)}
			<div class="flex not-first:mt-4 items-end">
				<div class="flex items-center gap-1 flex-none w-20 font-bold text-sm">
					{#if isLowValue}
						<ArrowDownIcon class="size-4" />
						Low:
					{/if}
				</div>
				<IndicatorPercentChart {label} {percent} />
			</div>
		{/each}
	{/if}

	{#if remainders.length > 0}
		<hr class="mb-6" />
		{#each remainders as { value, label, percent } (value)}
			<div class="flex mt-4">
				<div class="flex-none w-20 font-bold text-sm"></div>
				<IndicatorPercentChart {label} {percent} />
			</div>
		{/each}
	{/if}
</div>

// ui/src/content/IndicatorsTab/IndicatorPercentTable.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Box, Flex, Text, Divider } from 'theme-ui'
import {
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
} from '@emotion-icons/fa-solid'
import styled from '@emotion/styled'

import { sum } from 'util/data'
import { formatPercent } from 'util/format'

import IndicatorPercentChart from './IndicatorPercentChart'

const labelCSS = {
  flex: '0 0 auto',
  width: '5em',
  fontWeight: 'bold',
  fontSize: 0,
}

const ArrowUp = styled(ArrowUpIcon)({
  width: '1em',
  height: '1em',
  margin: 0,
  flex: '0 0 auto',
})

const ArrowDown = styled(ArrowDownIcon)({
  width: '1em',
  height: '1em',
  margin: 0,
  flex: '0 0 auto',
})

const IndicatorPercentTable = ({ type, values, goodThreshold }) => {
  // remainder values, like area outside SE, are assigned values < 0
  const remainders = values.filter(({ value }) => value < 0)

  if (goodThreshold === null) {
    return (
      <Box sx={{ my: '2rem' }}>
        {values
          .filter(({ value }) => value >= 0)
          .map(({ value, label, percent, isHighValue, isLowValue }) => (
            <Flex
              key={value || label}
              sx={{
                alignItems: isLowValue ? 'flex-end' : 'flex-start',
                '&:not(:first-of-type)': { mt: '1rem' },
              }}
            >
              <Text sx={labelCSS}>
                {isHighValue && (
                  <Flex sx={{ alignItems: 'center' }}>
                    <ArrowUp />
                    <Text sx={{ ml: '0.1rem' }}>High:</Text>
                  </Flex>
                )}
                {isLowValue && (
                  <Flex sx={{ alignItems: 'center' }}>
                    <ArrowDown />
                    <Text sx={{ ml: '0.1rem' }}>Low:</Text>
                  </Flex>
                )}
              </Text>
              <IndicatorPercentChart
                value={value}
                label={label}
                percent={percent}
              />
            </Flex>
          ))}

        {remainders.length > 0 ? (
          <>
            <Divider variant="styles.hr.dashed" sx={{ mb: '1.5rem' }} />
            <Box>
              {remainders.map(({ value, label, percent }) => (
                <Flex key={value || label} sx={{ mt: '1rem' }}>
                  <Text sx={labelCSS} />
                  <IndicatorPercentChart
                    value={value}
                    label={label}
                    percent={percent}
                    color="grey.4"
                  />
                </Flex>
              ))}
            </Box>
          </>
        ) : null}
      </Box>
    )
  }

  const goodPercents = values.filter(({ value }) => value >= goodThreshold)
  const notGoodPercents = values.filter(
    ({ value }) => value >= 0 && value < goodThreshold
  )

  const totalGoodPercent = sum(goodPercents.map(({ percent }) => percent))
  const totalNotGoodPercent = sum(notGoodPercents.map(({ percent }) => percent))

  return (
    <Box sx={{ my: '2rem' }}>
      {goodPercents.map(({ value, label, percent, isHighValue }) => (
        <Flex
          key={value || label}
          sx={{ '&:not(:first-of-type)': { mt: '1rem' } }}
        >
          <Text sx={labelCSS}>
            {isHighValue && (
              <Flex sx={{ alignItems: 'center' }}>
                <ArrowUp />
                <Text sx={{ ml: '0.1rem' }}>High:</Text>
              </Flex>
            )}
          </Text>
          <IndicatorPercentChart
            value={value}
            label={label}
            percent={percent}
          />
        </Flex>
      ))}

      <Box sx={{ mt: '1.5rem', color: 'grey.7', fontSize: 0 }}>
        <Flex sx={{ justifyContent: 'center', alignItems: 'center' }}>
          <ArrowUp />
          <Text sx={{ width: '14em', ml: '0.1em' }}>
            {formatPercent(totalGoodPercent)}% in good condition
          </Text>
        </Flex>

        <Box
          sx={{
            borderBottom: '1px dashed',
            borderBottomColor: 'grey.6',
            height: '1px',
            my: '0.25rem',
          }}
        />

        <Flex sx={{ justifyContent: 'center', alignItems: 'center' }}>
          <ArrowDown />
          <Text sx={{ width: '14em', ml: '0.1em' }}>
            {formatPercent(totalNotGoodPercent)}% not in good condition
          </Text>
        </Flex>
      </Box>

      {notGoodPercents.map(({ value, label, percent, isLowValue }) => (
        <Flex key={value || label} sx={{ mt: '1rem', alignItems: 'flex-end' }}>
          <Text sx={labelCSS}>
            {isLowValue && (
              <Flex sx={{ alignItems: 'center' }}>
                <ArrowDown />
                <Text sx={{ ml: '0.1rem' }}>Low:</Text>
              </Flex>
            )}
          </Text>
          <IndicatorPercentChart
            value={value}
            label={label}
            percent={percent}
          />
        </Flex>
      ))}

      {remainders.length > 0 ? (
        <>
          <Divider variant="styles.hr.dashed" sx={{ mb: '1.5rem' }} />
          <Box>
            {remainders.map(({ value, label, percent }) => (
              <Flex key={value || label} sx={{ mt: '1rem' }}>
                <Text sx={labelCSS} />
                <IndicatorPercentChart
                  value={value}
                  label={label}
                  percent={percent}
                  percentSuffix={type === 'pixel' ? '' : 'of area'}
                  color="grey.4"
                />
              </Flex>
            ))}
          </Box>
        </>
      ) : null}
    </Box>
  )
}

IndicatorPercentTable.propTypes = {
  type: PropTypes.string.isRequired,
  values: PropTypes.arrayOf(
    PropTypes.shape({
      value: PropTypes.number, // if <0, it is a remainder value
      label: PropTypes.string.isRequired,
      percent: PropTypes.number.isRequired,
      isHighValue: PropTypes.bool,
      isLowValue: PropTypes.bool,
    })
  ).isRequired,
  goodThreshold: PropTypes.number,
}

IndicatorPercentTable.defaultProps = {
  goodThreshold: null,
}

export default IndicatorPercentTable
